// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AdminEmailSubscriptionSubscriber{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AdminEmailSubscriptionSubscriberParameters are the configurable fields of a AdminEmailSubscriptionSubscriber.
//
// These are the fields of the create request body (CreateAnEmailSubscriberRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AdminEmailSubscriptionSubscriberObservation instead.
type AdminEmailSubscriptionSubscriberParameters struct {
	// EmailSubscriptionId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="emailSubscriptionId is immutable"
	EmailSubscriptionId string `json:"emailSubscriptionId"`

	// Name
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Email
	// +kubebuilder:validation:Required
	Email string `json:"email"`
}

// AdminEmailSubscriptionSubscriberObservation are the observable fields of a AdminEmailSubscriptionSubscriber.
//
// These are the fields of the read response (AdminEmailSubscriberModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AdminEmailSubscriptionSubscriberObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Email
	Email string `json:"email,omitempty"`
}

// A AdminEmailSubscriptionSubscriberSpec defines the desired state of a AdminEmailSubscriptionSubscriber.
type AdminEmailSubscriptionSubscriberSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AdminEmailSubscriptionSubscriberParameters `json:"forProvider"`
}

// A AdminEmailSubscriptionSubscriberStatus represents the observed state of a AdminEmailSubscriptionSubscriber.
type AdminEmailSubscriptionSubscriberStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AdminEmailSubscriptionSubscriberObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AdminEmailSubscriptionSubscriber is a managed OrangeHRM adminEmailSubscriptionSubscriber.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AdminEmailSubscriptionSubscriber struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AdminEmailSubscriptionSubscriberSpec   `json:"spec"`
	Status AdminEmailSubscriptionSubscriberStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdminEmailSubscriptionSubscriberList contains a list of AdminEmailSubscriptionSubscriber
type AdminEmailSubscriptionSubscriberList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdminEmailSubscriptionSubscriber `json:"items"`
}

// AdminEmailSubscriptionSubscriber type metadata.
var (
	AdminEmailSubscriptionSubscriberKind             = reflect.TypeOf(AdminEmailSubscriptionSubscriber{}).Name()
	AdminEmailSubscriptionSubscriberGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdminEmailSubscriptionSubscriberKind}.String()
	AdminEmailSubscriptionSubscriberKindAPIVersion   = AdminEmailSubscriptionSubscriberKind + "." + SchemeGroupVersion.String()
	AdminEmailSubscriptionSubscriberGroupVersionKind = SchemeGroupVersion.WithKind(AdminEmailSubscriptionSubscriberKind)
)

func init() {
	SchemeBuilder.Register(&AdminEmailSubscriptionSubscriber{}, &AdminEmailSubscriptionSubscriberList{})
}
