// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AttendanceRecord{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AttendanceRecordParameters are the configurable fields of a AttendanceRecord.
//
// These are the fields of the create request body (), which is
// exactly what a person may write. Anything the server assigns is in
// AttendanceRecordObservation instead.
type AttendanceRecordParameters struct {
}

// AttendanceRecordObservation are the observable fields of a AttendanceRecord.
//
// These are the fields of the read response (AttendanceDetailedAttendanceRecordModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AttendanceRecordObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// PunchIn
	PunchIn string `json:"punchIn,omitempty"`

	// PunchOut
	PunchOut string `json:"punchOut,omitempty"`

	// State
	State string `json:"state,omitempty"`

	// Employee
	Employee string `json:"employee,omitempty"`
}

// A AttendanceRecordSpec defines the desired state of a AttendanceRecord.
type AttendanceRecordSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AttendanceRecordParameters `json:"forProvider"`
}

// A AttendanceRecordStatus represents the observed state of a AttendanceRecord.
type AttendanceRecordStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AttendanceRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AttendanceRecord is a managed OrangeHRM attendanceRecord.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AttendanceRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AttendanceRecordSpec   `json:"spec"`
	Status AttendanceRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AttendanceRecordList contains a list of AttendanceRecord
type AttendanceRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AttendanceRecord `json:"items"`
}

// AttendanceRecord type metadata.
var (
	AttendanceRecordKind             = reflect.TypeOf(AttendanceRecord{}).Name()
	AttendanceRecordGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AttendanceRecordKind}.String()
	AttendanceRecordKindAPIVersion   = AttendanceRecordKind + "." + SchemeGroupVersion.String()
	AttendanceRecordGroupVersionKind = SchemeGroupVersion.WithKind(AttendanceRecordKind)
)

func init() {
	SchemeBuilder.Register(&AttendanceRecord{}, &AttendanceRecordList{})
}
