// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AdminWorkShift{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AdminWorkShiftParameters are the configurable fields of a AdminWorkShift.
//
// These are the fields of the create request body (CreateAWorkShiftRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AdminWorkShiftObservation instead.
type AdminWorkShiftParameters struct {
	// Name
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Name string `json:"name"`

	// HoursPerDay
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	HoursPerDay string `json:"hoursPerDay"`

	// StartTime
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	StartTime string `json:"startTime"`

	// EndTime
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	EndTime string `json:"endTime"`

	// EmpNumbers
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	EmpNumbers string `json:"empNumbers,omitempty"`
}

// AdminWorkShiftObservation are the observable fields of a AdminWorkShift.
//
// These are the fields of the read response (AdminWorkShiftDetailedModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AdminWorkShiftObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// HoursPerDay
	HoursPerDay float64 `json:"hoursPerDay,omitempty"`

	// StartTime
	StartTime string `json:"startTime,omitempty"`

	// EndTime
	EndTime string `json:"endTime,omitempty"`

	// Employees
	Employees string `json:"employees,omitempty"`
}

// A AdminWorkShiftSpec defines the desired state of a AdminWorkShift.
type AdminWorkShiftSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AdminWorkShiftParameters `json:"forProvider"`
}

// A AdminWorkShiftStatus represents the observed state of a AdminWorkShift.
type AdminWorkShiftStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AdminWorkShiftObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AdminWorkShift is a managed OrangeHRM adminWorkShift.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AdminWorkShift struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AdminWorkShiftSpec   `json:"spec"`
	Status AdminWorkShiftStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdminWorkShiftList contains a list of AdminWorkShift
type AdminWorkShiftList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdminWorkShift `json:"items"`
}

// AdminWorkShift type metadata.
var (
	AdminWorkShiftKind             = reflect.TypeOf(AdminWorkShift{}).Name()
	AdminWorkShiftGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdminWorkShiftKind}.String()
	AdminWorkShiftKindAPIVersion   = AdminWorkShiftKind + "." + SchemeGroupVersion.String()
	AdminWorkShiftGroupVersionKind = SchemeGroupVersion.WithKind(AdminWorkShiftKind)
)

func init() {
	SchemeBuilder.Register(&AdminWorkShift{}, &AdminWorkShiftList{})
}
