//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShift) DeepCopyInto(out *AdminWorkShift) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShift.
func (in *AdminWorkShift) DeepCopy() *AdminWorkShift {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminWorkShift) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShiftList) DeepCopyInto(out *AdminWorkShiftList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdminWorkShift, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShiftList.
func (in *AdminWorkShiftList) DeepCopy() *AdminWorkShiftList {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShiftList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminWorkShiftList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShiftObservation) DeepCopyInto(out *AdminWorkShiftObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShiftObservation.
func (in *AdminWorkShiftObservation) DeepCopy() *AdminWorkShiftObservation {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShiftObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShiftParameters) DeepCopyInto(out *AdminWorkShiftParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShiftParameters.
func (in *AdminWorkShiftParameters) DeepCopy() *AdminWorkShiftParameters {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShiftParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShiftSpec) DeepCopyInto(out *AdminWorkShiftSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShiftSpec.
func (in *AdminWorkShiftSpec) DeepCopy() *AdminWorkShiftSpec {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShiftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminWorkShiftStatus) DeepCopyInto(out *AdminWorkShiftStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminWorkShiftStatus.
func (in *AdminWorkShiftStatus) DeepCopy() *AdminWorkShiftStatus {
	if in == nil {
		return nil
	}
	out := new(AdminWorkShiftStatus)
	in.DeepCopyInto(out)
	return out
}
