// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Lifecycle{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// LifecycleParameters are the configurable fields of a Lifecycle.
//
// These are the fields of the create request body (LifecyclesPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// LifecycleObservation instead.
type LifecycleParameters struct {
	// Name
	// +kubebuilder:validation:Required
	Name string `json:"Name"`

	// Type
	// +kubebuilder:validation:Required
	Type string `json:"Type"`
}

// LifecycleObservation are the observable fields of a Lifecycle.
//
// These are the fields of the read response (LifecycleDocument) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type LifecycleObservation struct {
	// Type
	Type string `json:"type,omitempty"`

	// Initial Statuses a new object may start in.
	Initial string `json:"initial,omitempty"`

	// Active Statuses meaning work is ongoing.
	Active string `json:"active,omitempty"`

	// Inactive Statuses meaning work has stopped.
	Inactive string `json:"inactive,omitempty"`

	// Defaults Which status an action moves an object to.
	Defaults string `json:"defaults,omitempty"`

	// Transitions Which statuses each status may move to. The empty key is the transition into the lifecycle.
	Transitions string `json:"transitions,omitempty"`

	// Rights The right required to make a transition.
	Rights string `json:"rights,omitempty"`

	// Actions The transitions offered in the UI, as alternating \&quot;from -&gt; to\&quot; strings and their configuration.
	Actions string `json:"actions,omitempty"`

	// Colors A colour per status, as shown in the UI.
	Colors string `json:"colors,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// CanonicalCase The capitalisation RT treats as canonical for each status, keyed by the lower-case form.
	CanonicalCase string `json:"canonical_case,omitempty"`

	// Url An URL pointing somewhere in the web
	Url string `json:"_url,omitempty"`
}

// A LifecycleSpec defines the desired state of a Lifecycle.
type LifecycleSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              LifecycleParameters `json:"forProvider"`
}

// A LifecycleStatus represents the observed state of a Lifecycle.
type LifecycleStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 LifecycleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Lifecycle is a managed RT lifecycle.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Lifecycle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   LifecycleSpec   `json:"spec"`
	Status LifecycleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LifecycleList contains a list of Lifecycle
type LifecycleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Lifecycle `json:"items"`
}

// Lifecycle type metadata.
var (
	LifecycleKind             = reflect.TypeOf(Lifecycle{}).Name()
	LifecycleGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LifecycleKind}.String()
	LifecycleKindAPIVersion   = LifecycleKind + "." + SchemeGroupVersion.String()
	LifecycleGroupVersionKind = SchemeGroupVersion.WithKind(LifecycleKind)
)

func init() {
	SchemeBuilder.Register(&Lifecycle{}, &LifecycleList{})
}
