// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &RecruitmentVacancy{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// RecruitmentVacancyParameters are the configurable fields of a RecruitmentVacancy.
//
// These are the fields of the create request body (CreateAVacancyRequest), which is
// exactly what a person may write. Anything the server assigns is in
// RecruitmentVacancyObservation instead.
type RecruitmentVacancyParameters struct {
	// Name
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Name string `json:"name"`

	// Status
	// +kubebuilder:validation:Required
	Status bool `json:"status"`

	// JobTitleId
	// +kubebuilder:validation:Required
	JobTitleId int64 `json:"jobTitleId"`

	// IsPublished
	// +kubebuilder:validation:Required
	IsPublished bool `json:"isPublished"`

	// Description
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Description string `json:"description,omitempty"`

	// NumOfPositions
	// +optional
	NumOfPositions int64 `json:"numOfPositions,omitempty"`

	// EmployeeId
	// +kubebuilder:validation:Required
	EmployeeId int64 `json:"employeeId"`
}

// RecruitmentVacancyObservation are the observable fields of a RecruitmentVacancy.
//
// These are the fields of the read response (RecruitmentVacancyDetailedModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type RecruitmentVacancyObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// NumOfPositions
	NumOfPositions int64 `json:"numOfPositions,omitempty"`

	// Status
	Status bool `json:"status,omitempty"`

	// IsPublished
	IsPublished bool `json:"isPublished,omitempty"`

	// JobTitle
	JobTitle string `json:"jobTitle,omitempty"`

	// HiringManager
	HiringManager string `json:"hiringManager,omitempty"`
}

// A RecruitmentVacancySpec defines the desired state of a RecruitmentVacancy.
type RecruitmentVacancySpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              RecruitmentVacancyParameters `json:"forProvider"`
}

// A RecruitmentVacancyStatus represents the observed state of a RecruitmentVacancy.
type RecruitmentVacancyStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 RecruitmentVacancyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A RecruitmentVacancy is a managed OrangeHRM recruitmentVacancy.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type RecruitmentVacancy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RecruitmentVacancySpec   `json:"spec"`
	Status RecruitmentVacancyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecruitmentVacancyList contains a list of RecruitmentVacancy
type RecruitmentVacancyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RecruitmentVacancy `json:"items"`
}

// RecruitmentVacancy type metadata.
var (
	RecruitmentVacancyKind             = reflect.TypeOf(RecruitmentVacancy{}).Name()
	RecruitmentVacancyGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RecruitmentVacancyKind}.String()
	RecruitmentVacancyKindAPIVersion   = RecruitmentVacancyKind + "." + SchemeGroupVersion.String()
	RecruitmentVacancyGroupVersionKind = SchemeGroupVersion.WithKind(RecruitmentVacancyKind)
)

func init() {
	SchemeBuilder.Register(&RecruitmentVacancy{}, &RecruitmentVacancyList{})
}
