// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAModuleRequest is the UpdateAModuleRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAModuleRequest struct {
	Admin       bool `json:"admin"`
	Pim         bool `json:"pim"`
	Leave       bool `json:"leave"`
	Time        bool `json:"time"`
	Recruitment bool `json:"recruitment"`
	Performance bool `json:"performance"`
	Maintenance bool `json:"maintenance"`
	Mobile      bool `json:"mobile"`
	Directory   bool `json:"directory"`
	Claim       bool `json:"claim"`
	Buzz        bool `json:"buzz"`
}
