// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAvailableEmployees200Response is the ListAvailableEmployees200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAvailableEmployees200Response struct {
	Data []PimEmployeeAllowedReportToEmployeeModel `json:"data"`
	Meta ListAvailableEmployees200ResponseMeta     `json:"meta,omitempty"`
}
