// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PerformanceEmployeeTrackerModel is the PerformanceEmployeeTrackerModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PerformanceEmployeeTrackerModel struct {
	Id           int32                                    `json:"id,omitempty"`
	Title        LooseString                              `json:"title,omitempty"`
	Employee     *PerformanceEmployeeTrackerModelEmployee `json:"employee,omitempty"`
	AddedDate    float32                                  `json:"addedDate,omitempty"`
	ModifiedDate float32                                  `json:"modifiedDate,omitempty"`
}
