// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UnlikeALikedSharePost200ResponseData is the UnlikeALikedSharePost200ResponseData schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UnlikeALikedSharePost200ResponseData struct {
	ShareId int32 `json:"shareId,omitempty"`
}
