// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListMobileMenuItems200ResponseMeta is the ListMobileMenuItems200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListMobileMenuItems200ResponseMeta struct {
	IsLeavePeriodDefined     bool `json:"isLeavePeriodDefined,omitempty"`
	IsTimesheetPeriodDefined bool `json:"isTimesheetPeriodDefined,omitempty"`
}
