// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllI18nGroups200Response is the ListAllI18nGroups200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllI18nGroups200Response struct {
	Data []AdminI18NGroupModel                  `json:"data,omitempty"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
