// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateLdapConfigurationRequestUserLookupSettingsInner is the UpdateLdapConfigurationRequestUserLookupSettingsInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateLdapConfigurationRequestUserLookupSettingsInner struct {
	BaseDN                  LooseString                                                                         `json:"baseDN,omitempty"`
	SearchScope             LooseString                                                                         `json:"searchScope,omitempty"`
	UserNameAttribute       LooseString                                                                         `json:"userNameAttribute,omitempty"`
	UserSearchFilter        LooseString                                                                         `json:"userSearchFilter,omitempty"`
	UserUniqueIdAttribute   LooseString                                                                         `json:"userUniqueIdAttribute,omitempty"`
	EmployeeSelectorMapping []UpdateLdapConfigurationRequestUserLookupSettingsInnerEmployeeSelectorMappingInner `json:"employeeSelectorMapping"`
}
