// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AddALanguageToAnEmployee400Response is the AddALanguageToAnEmployee400Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AddALanguageToAnEmployee400Response struct {
	Error AddALanguageToAnEmployee400ResponseError `json:"error,omitempty"`
}
