// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// DeleteACommentOnAPost200ResponseData is the DeleteACommentOnAPost200ResponseData schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type DeleteACommentOnAPost200ResponseData struct {
	CommentId int32 `json:"commentId,omitempty"`
	ShareId   int32 `json:"shareId,omitempty"`
}
