// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimEmpUsTaxExemptionModelWorkState is the PimEmpUsTaxExemptionModelWorkState schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimEmpUsTaxExemptionModelWorkState struct {
	Code LooseString `json:"code,omitempty"`
	Name LooseString `json:"name,omitempty"`
}
