// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllowedSkillsForAnEmployee200Response is the ListAllowedSkillsForAnEmployee200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllowedSkillsForAnEmployee200Response struct {
	Data []PimEmployeeAllowedSkillModel                 `json:"data"`
	Meta *ListAllowedSkillsForAnEmployee200ResponseMeta `json:"meta,omitempty"`
}
