// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// TimeTimesheetActionLogModel is the TimeTimesheetActionLogModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TimeTimesheetActionLogModel struct {
	Id                int32                                                   `json:"id,omitempty"`
	Action            *AttendanceDetailedAttendanceRecordModelPunchInTimezone `json:"action,omitempty"`
	Comment           LooseString                                             `json:"comment,omitempty"`
	Date              LooseString                                             `json:"date,omitempty"`
	PerformedEmployee *GetMyTimeAtWork200ResponseMetaCurrentUser              `json:"performedEmployee,omitempty"`
}
