// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllMemberships200Response is the ListAllMemberships200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllMemberships200Response struct {
	Data []AdminMembershipModel                 `json:"data"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
