// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateMyLeaveRequest400Response is the UpdateMyLeaveRequest400Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateMyLeaveRequest400Response struct {
	Error UpdateMyLeaveRequest400ResponseError `json:"error,omitempty"`
}
