// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// BuzzFeedPostModelTextStats is the BuzzFeedPostModelTextStats schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type BuzzFeedPostModelTextStats struct {
	NumOfLikes    int32 `json:"numOfLikes,omitempty"`
	NumOfComments int32 `json:"numOfComments,omitempty"`
	NumOfShares   int32 `json:"numOfShares,omitempty"`
}
