// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// SlackRegistrationModel is the SlackRegistrationModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type SlackRegistrationModel struct {
	Id            int32                                 `json:"id,omitempty"`
	Provider      LooseString                           `json:"provider,omitempty"`
	EventType     LooseString                           `json:"eventType,omitempty"`
	WebhookUrl    LooseString                           `json:"webhookUrl,omitempty"`
	ChannelLabel  LooseString                           `json:"channelLabel,omitempty"`
	Subunits      []SlackRegistrationModelSubunitsInner `json:"subunits"`
	Timezone      LooseString                           `json:"timezone,omitempty"`
	DailySendTime LooseString                           `json:"dailySendTime,omitempty"`
	Active        bool                                  `json:"active"`
}
