// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AttendanceDetailedAttendanceRecordModelPunchIn is the AttendanceDetailedAttendanceRecordModelPunchIn schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AttendanceDetailedAttendanceRecordModelPunchIn struct {
	UtcDate        LooseString                                             `json:"utcDate,omitempty"`
	UtcTime        LooseString                                             `json:"utcTime,omitempty"`
	UserDate       LooseString                                             `json:"userDate,omitempty"`
	UserTime       LooseString                                             `json:"userTime,omitempty"`
	TimezoneOffset LooseString                                             `json:"timezoneOffset,omitempty"`
	Timezone       *AttendanceDetailedAttendanceRecordModelPunchInTimezone `json:"timezone,omitempty"`
	Note           LooseString                                             `json:"note,omitempty"`
}
