// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateWorkWeekRequest is the UpdateWorkWeekRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateWorkWeekRequest struct {
	Monday    int32 `json:"monday,omitempty"`
	Tuesday   int32 `json:"tuesday,omitempty"`
	Wednesday int32 `json:"wednesday,omitempty"`
	Thursday  int32 `json:"thursday,omitempty"`
	Friday    int32 `json:"friday,omitempty"`
	Saturday  int32 `json:"saturday,omitempty"`
	Sunday    int32 `json:"sunday,omitempty"`
}
