// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateAPerformanceTrackerRequest is the CreateAPerformanceTrackerRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateAPerformanceTrackerRequest struct {
	TrackerName LooseString `json:"trackerName,omitempty"`
	EmpNumber   int32       `json:"empNumber,omitempty"`
	Reviewers   []int32     `json:"reviewers"`
}
