// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesEmploymentContract200Response is the UpdateAnEmployeesEmploymentContract200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesEmploymentContract200Response struct {
	Data      *PimEmploymentContractModel `json:"data,omitempty"`
	EmpNumber int32                       `json:"empNumber,omitempty"`
}
