// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateASubunitRequest is the CreateASubunitRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateASubunitRequest struct {
	Name        LooseString `json:"name,omitempty"`
	Description LooseString `json:"description,omitempty"`
	ParentId    int32       `json:"parentId,omitempty"`
	UnitId      LooseString `json:"unitId,omitempty"`
}
