// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// SlackRegistrationModel is the SlackRegistrationModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type SlackRegistrationModel struct {
	Id            int32                                 `json:"id,omitempty"`
	Provider      string                                `json:"provider,omitempty"`
	EventType     string                                `json:"eventType,omitempty"`
	WebhookUrl    string                                `json:"webhookUrl,omitempty"`
	ChannelLabel  string                                `json:"channelLabel,omitempty"`
	Subunits      []SlackRegistrationModelSubunitsInner `json:"subunits,omitempty"`
	Timezone      string                                `json:"timezone,omitempty"`
	DailySendTime string                                `json:"dailySendTime,omitempty"`
	Active        bool                                  `json:"active,omitempty"`
}
