// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyTimeAtWork200Response is the GetMyTimeAtWork200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyTimeAtWork200Response struct {
	Data []GetMyTimeAtWork200ResponseDataInner `json:"data"`
	Meta GetMyTimeAtWork200ResponseMeta        `json:"meta,omitempty"`
}
