// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// RecruitmentCandidateDetailedModel is the RecruitmentCandidateDetailedModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type RecruitmentCandidateDetailedModel struct {
	Id                int32                                          `json:"id,omitempty"`
	FirstName         LooseString                                    `json:"firstName,omitempty"`
	MiddleName        LooseString                                    `json:"middleName,omitempty"`
	LastName          LooseString                                    `json:"lastName,omitempty"`
	Email             LooseString                                    `json:"email,omitempty"`
	ContactNumber     LooseString                                    `json:"contactNumber,omitempty"`
	Comment           LooseString                                    `json:"comment,omitempty"`
	Keywords          LooseString                                    `json:"keywords,omitempty"`
	ModeOfApplication LooseString                                    `json:"modeOfApplication,omitempty"`
	DateOfApplication LooseString                                    `json:"dateOfApplication,omitempty"`
	Vacancy           *RecruitmentCandidateDetailedModelVacancy      `json:"vacancy,omitempty"`
	Status            []RecruitmentCandidateDetailedModelStatusInner `json:"status"`
	HasAttachment     bool                                           `json:"hasAttachment"`
	ConsentToKeepData bool                                           `json:"consentToKeepData"`
}
