// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateLdapConfigurationRequestDataMapping is the UpdateLdapConfigurationRequestDataMapping schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateLdapConfigurationRequestDataMapping struct {
	FirstName  LooseString `json:"firstName,omitempty"`
	MiddleName LooseString `json:"middleName,omitempty"`
	LastName   LooseString `json:"lastName,omitempty"`
	UserStatus LooseString `json:"userStatus,omitempty"`
	WorkEmail  LooseString `json:"workEmail,omitempty"`
	EmployeeId LooseString `json:"employeeId,omitempty"`
}
