// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetLeaveReportData200ResponseDataInnerUrl is the GetLeaveReportData200ResponseDataInnerUrl schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetLeaveReportData200ResponseDataInnerUrl struct {
	EntitlementDays     LooseString `json:"entitlementDays,omitempty"`
	PendingApprovalDays LooseString `json:"pendingApprovalDays,omitempty"`
	ScheduledDays       LooseString `json:"scheduledDays,omitempty"`
	TakenDays           LooseString `json:"takenDays,omitempty"`
}
