// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ApplyForLeaveRequest is the ApplyForLeaveRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ApplyForLeaveRequest struct {
	Comment       string                           `json:"comment,omitempty"`
	Duration      *ApplyForLeaveRequestDuration    `json:"duration,omitempty"`
	EndDuration   *ApplyForLeaveRequestEndDuration `json:"endDuration,omitempty"`
	PartialOption string                           `json:"partialOption,omitempty"`
	FromDate      string                           `json:"fromDate,omitempty"`
	ToDate        string                           `json:"toDate,omitempty"`
	LeaveTypeId   int32                            `json:"leaveTypeId,omitempty"`
}
