// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PerformancePerformanceTrackReviewerModel is the PerformancePerformanceTrackReviewerModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PerformancePerformanceTrackReviewerModel struct {
	EmpNumber     int32  `json:"empNumber,omitempty"`
	EmployeeId    string `json:"employeeId,omitempty"`
	FirstName     string `json:"firstName,omitempty"`
	LastName      string `json:"lastName,omitempty"`
	MiddleName    string `json:"middleName,omitempty"`
	TerminationId int32  `json:"terminationId,omitempty"`
}
