// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AdminLocationModel is the AdminLocationModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AdminLocationModel struct {
	Id            int32                      `json:"id,omitempty"`
	Name          LooseString                `json:"name,omitempty"`
	Country       *AdminLocationModelCountry `json:"country,omitempty"`
	Province      LooseString                `json:"province,omitempty"`
	City          LooseString                `json:"city,omitempty"`
	Address       LooseString                `json:"address,omitempty"`
	ZipCode       LooseString                `json:"zipCode,omitempty"`
	Phone         LooseString                `json:"phone,omitempty"`
	Fax           LooseString                `json:"fax,omitempty"`
	Note          LooseString                `json:"note,omitempty"`
	NoOfEmployees int32                      `json:"noOfEmployees,omitempty"`
}
