// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAUserRequest is the UpdateAUserRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAUserRequest struct {
	Username   LooseString `json:"username,omitempty"`
	Password   LooseString `json:"password,omitempty"`
	Status     bool        `json:"status"`
	UserRoleId int32       `json:"userRoleId,omitempty"`
	EmpNumber  int32       `json:"empNumber,omitempty"`
}
