// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateATimesheetCommentRequest is the UpdateATimesheetCommentRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateATimesheetCommentRequest struct {
	ProjectId  int32       `json:"projectId,omitempty"`
	ActivityId int32       `json:"activityId,omitempty"`
	Date       LooseString `json:"date,omitempty"`
	Comment    LooseString `json:"comment,omitempty"`
}
