// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimPimDefinedReportModel is the PimPimDefinedReportModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimPimDefinedReportModel struct {
	Id   int32  `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
