// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// LeaveLeaveDetailedModelDates is the LeaveLeaveDetailedModelDates schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LeaveLeaveDetailedModelDates struct {
	FromDate     LooseString                          `json:"fromDate,omitempty"`
	ToDate       LooseString                          `json:"toDate,omitempty"`
	DurationType *LeaveEmployeeLeaveModelDurationType `json:"durationType,omitempty"`
	StartTime    LooseString                          `json:"startTime,omitempty"`
}
