// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetAnEmployeesAttachmentOnAScreen200ResponseMeta is the GetAnEmployeesAttachmentOnAScreen200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetAnEmployeesAttachmentOnAScreen200ResponseMeta struct {
	EmpNumber int32       `json:"empNumber,omitempty"`
	Screen    LooseString `json:"screen,omitempty"`
}
