// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// LeaveBulkLeaveEntitlementMatchingEmployeeModelEntitlement is the LeaveBulkLeaveEntitlementMatchingEmployeeModelEntitlement schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LeaveBulkLeaveEntitlementMatchingEmployeeModelEntitlement struct {
	Current  int32 `json:"current,omitempty"`
	UpdateAs int32 `json:"updateAs,omitempty"`
}
