// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllEmailSubscribers200ResponseMeta is the ListAllEmailSubscribers200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllEmailSubscribers200ResponseMeta struct {
	Total int32  `json:"total,omitempty"`
	Name  string `json:"name,omitempty"`
}
