// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllCommentsForALeave200Response is the ListAllCommentsForALeave200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllCommentsForALeave200Response struct {
	Data LeaveLeaveCommentModel                 `json:"data,omitempty"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
