// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// EditAPostRequest is the EditAPostRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type EditAPostRequest struct {
	Text          string                                `json:"text,omitempty"`
	Type          string                                `json:"type,omitempty"`
	DeletedPhotos []BuzzPostPhotoEditDeletedPhotosInner `json:"deletedPhotos"`
	Photos        []Base64Attachment                    `json:"photos"`
	Link          string                                `json:"link,omitempty"`
}
