// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ClaimExpenseModel is the ClaimExpenseModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ClaimExpenseModel struct {
	Id           int32                          `json:"id,omitempty"`
	ClaimRequest *ClaimExpenseModelClaimRequest `json:"claimRequest,omitempty"`
	ExpenseType  *ClaimExpenseModelExpenseType  `json:"expenseType,omitempty"`
	Amount       float32                        `json:"amount,omitempty"`
	Note         string                         `json:"note,omitempty"`
}
