// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetAClaimEvent200ResponseMeta is the GetAClaimEvent200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetAClaimEvent200ResponseMeta struct {
	CanEdit bool `json:"canEdit"`
}
