// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// SendWorkspaceNotificationTestWithUrlRequest is the SendWorkspaceNotificationTestWithUrlRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type SendWorkspaceNotificationTestWithUrlRequest struct {
	EventType  LooseString `json:"eventType,omitempty"`
	WebhookUrl LooseString `json:"webhookUrl,omitempty"`
	Provider   LooseString `json:"provider,omitempty"`
}
