// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// TimeDetailedTimesheetModel is the TimeDetailedTimesheetModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TimeDetailedTimesheetModel struct {
	Project  *DashboardEmployeeOnLeaveListModelLeaveType         `json:"project,omitempty"`
	Customer *DashboardEmployeeOnLeaveListModelLeaveType         `json:"customer,omitempty"`
	Activity *DashboardEmployeeOnLeaveListModelLeaveType         `json:"activity,omitempty"`
	Total    *ListAnEmployeesAttendanceRecords200ResponseMetaSum `json:"total,omitempty"`
	Dates    map[string]TimeDetailedTimesheetModelDatesValue     `json:"dates"`
}
