// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetAnEmployeesUsTaxExpemptionDetails200Response is the GetAnEmployeesUsTaxExpemptionDetails200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetAnEmployeesUsTaxExpemptionDetails200Response struct {
	Data *PimEmpUsTaxExemptionModel                     `json:"data,omitempty"`
	Meta *GetAnEmployeesEmergencyContact200ResponseMeta `json:"meta,omitempty"`
}
