// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetLeaveReport200ResponseDataInnerHeadersInnerCellPropertiesClass is the GetLeaveReport200ResponseDataInnerHeadersInnerCellPropertiesClass schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetLeaveReport200ResponseDataInnerHeadersInnerCellPropertiesClass struct {
	CellAction bool `json:"cell-action,omitempty"`
}
