// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyDetails200ResponseData is the GetMyDetails200ResponseData schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyDetails200ResponseData struct {
	EmpNumber     interface{}                                `json:"empNumber,omitempty"`
	LastName      LooseString                                `json:"lastName,omitempty"`
	FirstName     LooseString                                `json:"firstName,omitempty"`
	MiddleName    LooseString                                `json:"middleName,omitempty"`
	EmployeeId    LooseString                                `json:"employeeId,omitempty"`
	TerminationId int32                                      `json:"terminationId,omitempty"`
	JobTitle      interface{}                                `json:"jobTitle,omitempty"`
	Subunit       interface{}                                `json:"subunit,omitempty"`
	EmpStatus     *PimEmployeeDetailedModelEmpStatus         `json:"empStatus,omitempty"`
	Supervisors   []PimEmployeeDetailedModelSupervisorsInner `json:"supervisors"`
}
