// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAnEmployeesSalaryComponents200Response is the ListAnEmployeesSalaryComponents200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAnEmployeesSalaryComponents200Response struct {
	Data *PimEmployeeSalaryModel                    `json:"data,omitempty"`
	Meta *GetAnEmployeesLeaveBalance200ResponseMeta `json:"meta,omitempty"`
}
