// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// InlineObject1Error is the InlineObject1Error schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type InlineObject1Error struct {
	Status  LooseString `json:"status,omitempty"`
	Message LooseString `json:"message,omitempty"`
}
