// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesEmploymentContractRequest is the UpdateAnEmployeesEmploymentContractRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesEmploymentContractRequest struct {
	StartDate                 LooseString       `json:"startDate,omitempty"`
	EndDate                   LooseString       `json:"endDate,omitempty"`
	CurrentContractAttachment LooseString       `json:"currentContractAttachment,omitempty"`
	ContractAttachment        *Base64Attachment `json:"contractAttachment,omitempty"`
}
