// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// BuzzPostVideoEdit is the BuzzPostVideoEdit schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type BuzzPostVideoEdit struct {
	Text LooseString `json:"text,omitempty"`
	Type LooseString `json:"type,omitempty"`
	Link LooseString `json:"link,omitempty"`
}
