// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimEmployeeDetailedModelSupervisorsInner is the PimEmployeeDetailedModelSupervisorsInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimEmployeeDetailedModelSupervisorsInner struct {
	EmpNumber  string `json:"empNumber,omitempty"`
	LastName   string `json:"lastName,omitempty"`
	FirstName  string `json:"firstName,omitempty"`
	MiddleName string `json:"middleName,omitempty"`
}
