// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// BuzzBuzzDetailedCommentModelComment is the BuzzBuzzDetailedCommentModelComment schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type BuzzBuzzDetailedCommentModelComment struct {
	Id          int32       `json:"id,omitempty"`
	Text        LooseString `json:"text,omitempty"`
	NumOfLikes  int32       `json:"numOfLikes,omitempty"`
	Liked       bool        `json:"liked"`
	CreatedDate LooseString `json:"createdDate,omitempty"`
	CreatedTime LooseString `json:"createdTime,omitempty"`
}
