// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesEducationalQualificationRequest is the UpdateAnEmployeesEducationalQualificationRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesEducationalQualificationRequest struct {
	EducationId int32       `json:"educationId,omitempty"`
	Institute   LooseString `json:"institute,omitempty"`
	Major       LooseString `json:"major,omitempty"`
	Year        int32       `json:"year,omitempty"`
	Score       LooseString `json:"score,omitempty"`
	StartDate   LooseString `json:"startDate,omitempty"`
	EndDate     LooseString `json:"endDate,omitempty"`
}
