// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllCandidates200ResponseDataInner is the ListAllCandidates200ResponseDataInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllCandidates200ResponseDataInner struct {
	Id                int32       `json:"id,omitempty"`
	FirstName         LooseString `json:"firstName,omitempty"`
	MiddleName        LooseString `json:"middleName,omitempty"`
	LastName          LooseString `json:"lastName,omitempty"`
	Email             LooseString `json:"email,omitempty"`
	DateOfApplication LooseString `json:"dateOfApplication,omitempty"`
	Vacancy           interface{} `json:"vacancy,omitempty"`
	Status            interface{} `json:"status"`
	HasAttachment     bool        `json:"hasAttachment"`
	Deletable         bool        `json:"deletable"`
	ContactNumber     LooseString `json:"contactNumber,omitempty"`
	Comment           LooseString `json:"comment,omitempty"`
	Keywords          LooseString `json:"keywords,omitempty"`
	ModeOfApplication LooseString `json:"modeOfApplication,omitempty"`
	ConsentToKeepData bool        `json:"consentToKeepData"`
}
