// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateLocalizationSettings200Response is the UpdateLocalizationSettings200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateLocalizationSettings200Response struct {
	Data AdminMembershipModel   `json:"data,omitempty"`
	Meta map[string]interface{} `json:"meta,omitempty"`
}
