// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnAttendanceRecordRequest is the UpdateAnAttendanceRecordRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnAttendanceRecordRequest struct {
	PunchInDate          LooseString `json:"punchInDate,omitempty"`
	PunchInTime          LooseString `json:"punchInTime,omitempty"`
	PunchInOffset        float32     `json:"punchInOffset,omitempty"`
	PunchInTimezoneName  LooseString `json:"punchInTimezoneName,omitempty"`
	PunchOutDate         LooseString `json:"punchOutDate,omitempty"`
	PunchOutTime         LooseString `json:"punchOutTime,omitempty"`
	PunchOutOffset       float32     `json:"punchOutOffset,omitempty"`
	PunchOutTimezoneName LooseString `json:"punchOutTimezoneName,omitempty"`
	PunchOutNote         LooseString `json:"punchOutNote,omitempty"`
}
