// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllKpis200Response is the ListAllKpis200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllKpis200Response struct {
	Data []PerformanceKpiModel                  `json:"data,omitempty"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
