// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ImportEmployeeRecords200ResponseMeta is the ImportEmployeeRecords200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ImportEmployeeRecords200ResponseMeta struct {
	Failed     int32   `json:"failed,omitempty"`
	FailedRows []int32 `json:"failedRows,omitempty"`
	Success    int32   `json:"success,omitempty"`
	Total      int32   `json:"total,omitempty"`
}
