// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AttendanceEmployeeAttendanceSummeryListModel is the AttendanceEmployeeAttendanceSummeryListModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AttendanceEmployeeAttendanceSummeryListModel struct {
	EmpNumber     int32                                               `json:"empNumber,omitempty"`
	LastName      LooseString                                         `json:"lastName,omitempty"`
	FirstName     LooseString                                         `json:"firstName,omitempty"`
	MiddleName    LooseString                                         `json:"middleName,omitempty"`
	EmployeeId    LooseString                                         `json:"employeeId,omitempty"`
	TerminationId int32                                               `json:"terminationId,omitempty"`
	Sum           *ListAnEmployeesAttendanceRecords200ResponseMetaSum `json:"sum,omitempty"`
}
