// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListMyClaimRequests200ResponseDataInner is the ListMyClaimRequests200ResponseDataInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListMyClaimRequests200ResponseDataInner struct {
	Id            int32                                     `json:"id,omitempty"`
	ReferenceId   int32                                     `json:"referenceId,omitempty"`
	ClaimEvent    *ClaimEmployeeClaimRequestModelClaimEvent `json:"claimEvent,omitempty"`
	CurrencyType  *ClaimEmployeeClaimRequestModelClaimEvent `json:"currencyType,omitempty"`
	Description   LooseString                               `json:"description,omitempty"`
	Status        LooseString                               `json:"status,omitempty"`
	Amount        float32                                   `json:"amount,omitempty"`
	SubmittedDate LooseString                               `json:"submittedDate,omitempty"`
}
