// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// Base64Attachment is the Base64Attachment schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type Base64Attachment struct {
	Name   LooseString `json:"name,omitempty"`
	Type   LooseString `json:"type,omitempty"`
	Base64 LooseString `json:"base64,omitempty"`
	Size   int32       `json:"size,omitempty"`
}
