// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateALogForAPerformanceTrackerRequest is the CreateALogForAPerformanceTrackerRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateALogForAPerformanceTrackerRequest struct {
	Achievement int32       `json:"achievement,omitempty"`
	Comment     LooseString `json:"comment,omitempty"`
	Log         LooseString `json:"log,omitempty"`
}
