// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// BuzzBuzzLikeOnShareModel is the BuzzBuzzLikeOnShareModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type BuzzBuzzLikeOnShareModel struct {
	Id          int32                                `json:"id,omitempty"`
	LikedAtDate string                               `json:"likedAtDate,omitempty"`
	LikedAtTime string                               `json:"likedAtTime,omitempty"`
	Share       *BuzzPostPhotoEditDeletedPhotosInner `json:"share,omitempty"`
	Employee    *BuzzBuzzLikeOnCommentModelEmployee  `json:"employee,omitempty"`
}
