// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// LdapLdapConfigModel is the LdapLdapConfigModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LdapLdapConfigModel struct {
	Enable                                bool                           `json:"enable,omitempty"`
	Hostname                              string                         `json:"hostname,omitempty"`
	Port                                  int32                          `json:"port,omitempty"`
	Encryption                            string                         `json:"encryption,omitempty"`
	LdapImplementation                    string                         `json:"ldapImplementation,omitempty"`
	BindAnonymously                       bool                           `json:"bindAnonymously,omitempty"`
	BindUserDN                            string                         `json:"bindUserDN,omitempty"`
	HasBindUserPassword                   bool                           `json:"hasBindUserPassword,omitempty"`
	UserLookupSettings                    []string                       `json:"userLookupSettings,omitempty"`
	DataMapping                           LdapLdapConfigModelDataMapping `json:"dataMapping,omitempty"`
	MergeLDAPUsersWithExistingSystemUsers bool                           `json:"mergeLDAPUsersWithExistingSystemUsers,omitempty"`
	SyncInterval                          int32                          `json:"syncInterval,omitempty"`
}
