// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// TestLdapConnectionRequest is the TestLdapConnectionRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TestLdapConnectionRequest struct {
	Hostname           LooseString                                        `json:"hostname,omitempty"`
	Port               int32                                              `json:"port,omitempty"`
	Encryption         LooseString                                        `json:"encryption,omitempty"`
	LdapImplementation LooseString                                        `json:"ldapImplementation,omitempty"`
	BindAnonymously    bool                                               `json:"bindAnonymously"`
	BindUserDN         LooseString                                        `json:"bindUserDN,omitempty"`
	BindUserPassword   LooseString                                        `json:"bindUserPassword,omitempty"`
	UserLookupSettings []TestLdapConnectionRequestUserLookupSettingsInner `json:"userLookupSettings"`
	DataMapping        *UpdateLdapConfigurationRequestDataMapping         `json:"dataMapping,omitempty"`
}
