// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetAnEmployeesContactDetails200Response is the GetAnEmployeesContactDetails200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetAnEmployeesContactDetails200Response struct {
	Data PimEmployeeContactDetailsModel `json:"data,omitempty"`
	Meta map[string]interface{}         `json:"meta,omitempty"`
}
