// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimCustomFieldModel is the PimCustomFieldModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimCustomFieldModel struct {
	Id        int32       `json:"id,omitempty"`
	FieldName LooseString `json:"fieldName,omitempty"`
	FieldType LooseString `json:"fieldType,omitempty"`
	ExtraData LooseString `json:"extraData,omitempty"`
	Screen    LooseString `json:"screen,omitempty"`
}
