// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateAnEmployeeRequest is the CreateAnEmployeeRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateAnEmployeeRequest struct {
	LastName   string           `json:"lastName,omitempty"`
	FirstName  string           `json:"firstName,omitempty"`
	MiddleName string           `json:"middleName,omitempty"`
	EmployeeId string           `json:"employeeId,omitempty"`
	EmpPicture Base64Attachment `json:"empPicture,omitempty"`
}
