// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateAnEmployeeRequest is the CreateAnEmployeeRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateAnEmployeeRequest struct {
	LastName   LooseString       `json:"lastName,omitempty"`
	FirstName  LooseString       `json:"firstName,omitempty"`
	MiddleName LooseString       `json:"middleName,omitempty"`
	EmployeeId LooseString       `json:"employeeId,omitempty"`
	EmpPicture *Base64Attachment `json:"empPicture,omitempty"`
}
