// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllLanguageRecords200Response is the ListAllLanguageRecords200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllLanguageRecords200Response struct {
	Data []AdminLanguageModel                   `json:"data"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
