// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// HireCandidate200Response is the HireCandidate200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type HireCandidate200Response struct {
	Data *RecruitmentCandidateHistoryDefaultModel `json:"data,omitempty"`
	Meta interface{}                              `json:"meta"`
}
