// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// RecruitmentCandidateHistoryListModel is the RecruitmentCandidateHistoryListModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type RecruitmentCandidateHistoryListModel struct {
	Id            int32                                             `json:"id,omitempty"`
	Action        GetAllowedActionsForCandidate200ResponseDataInner `json:"action,omitempty"`
	VacancyName   string                                            `json:"vacancyName,omitempty"`
	PerformedBy   GetMyTimeAtWork200ResponseMetaCurrentUser         `json:"performedBy,omitempty"`
	PerformedDate string                                            `json:"performedDate,omitempty"`
	Note          string                                            `json:"note,omitempty"`
	Editable      bool                                              `json:"editable"`
	Interview     RecruitmentCandidateHistoryListModelInterview     `json:"interview,omitempty"`
}
