// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ImportEmployeeRecords200Response is the ImportEmployeeRecords200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ImportEmployeeRecords200Response struct {
	Data []interface{}                        `json:"data,omitempty"`
	Meta ImportEmployeeRecords200ResponseMeta `json:"meta,omitempty"`
}
