// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ValidateI18nTranslation200Response is the ValidateI18nTranslation200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ValidateI18nTranslation200Response struct {
	Data *ValidateI18nTranslation200ResponseData `json:"data,omitempty"`
}
