// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyTimeAtWork200ResponseDataInnerWorkDay is the GetMyTimeAtWork200ResponseDataInnerWorkDay schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyTimeAtWork200ResponseDataInnerWorkDay struct {
	Id   string `json:"id,omitempty"`
	Day  string `json:"day,omitempty"`
	Date string `json:"date,omitempty"`
}
