// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateAnEmailSubscriber200Response is the CreateAnEmailSubscriber200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateAnEmailSubscriber200Response struct {
	Data AdminEmailSubscriberModel `json:"data,omitempty"`
	Meta interface{}               `json:"meta,omitempty"`
}
