// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetLeaveBalanceForALeaveType200ResponseMeta is the GetLeaveBalanceForALeaveType200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetLeaveBalanceForALeaveType200ResponseMeta struct {
	Employee  PimEmployeeModel    `json:"employee,omitempty"`
	LeaveType LeaveLeaveTypeModel `json:"leaveType,omitempty"`
}
