// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimEmployeeAttachmentModel is the PimEmployeeAttachmentModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimEmployeeAttachmentModel struct {
	Id             int32       `json:"id,omitempty"`
	Description    LooseString `json:"description,omitempty"`
	Filename       LooseString `json:"filename,omitempty"`
	Size           int32       `json:"size,omitempty"`
	FileType       LooseString `json:"fileType,omitempty"`
	AttachedBy     int32       `json:"attachedBy,omitempty"`
	AttachedByName LooseString `json:"attachedByName,omitempty"`
	AttachedTime   LooseString `json:"attachedTime,omitempty"`
	AttachedDate   LooseString `json:"attachedDate,omitempty"`
}
