// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// TestLdapConnectionRequestUserLookupSettingsInner is the TestLdapConnectionRequestUserLookupSettingsInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TestLdapConnectionRequestUserLookupSettingsInner struct {
	BaseDN                  string      `json:"baseDN,omitempty"`
	SearchScope             string      `json:"searchScope,omitempty"`
	UserNameAttribute       string      `json:"userNameAttribute,omitempty"`
	UserSearchFilter        string      `json:"userSearchFilter,omitempty"`
	UserUniqueIdAttribute   string      `json:"userUniqueIdAttribute,omitempty"`
	EmployeeSelectorMapping interface{} `json:"employeeSelectorMapping"`
}
