// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AdminWorkShiftDetailedModel is the AdminWorkShiftDetailedModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AdminWorkShiftDetailedModel struct {
	Id          int32              `json:"id,omitempty"`
	Name        string             `json:"name,omitempty"`
	HoursPerDay float32            `json:"hoursPerDay,omitempty"`
	StartTime   string             `json:"startTime,omitempty"`
	EndTime     string             `json:"endTime,omitempty"`
	Employees   []PimEmployeeModel `json:"employees"`
}
