// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetWorkWeek200ResponseData is the GetWorkWeek200ResponseData schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetWorkWeek200ResponseData struct {
	Var0      int32 `json:"0,omitempty"`
	Var1      int32 `json:"1,omitempty"`
	Var2      int32 `json:"2,omitempty"`
	Var3      int32 `json:"3,omitempty"`
	Var4      int32 `json:"4,omitempty"`
	Var5      int32 `json:"5,omitempty"`
	Var6      int32 `json:"6,omitempty"`
	Monday    int32 `json:"monday,omitempty"`
	Tuesday   int32 `json:"tuesday,omitempty"`
	Wednesday int32 `json:"wednesday,omitempty"`
	Thursday  int32 `json:"thursday,omitempty"`
	Friday    int32 `json:"friday,omitempty"`
	Saturday  int32 `json:"saturday,omitempty"`
	Sunday    int32 `json:"sunday,omitempty"`
}
