// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesWorkExperienceRecordRequest is the UpdateAnEmployeesWorkExperienceRecordRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesWorkExperienceRecordRequest struct {
	Company  string `json:"company,omitempty"`
	JobTitle string `json:"jobTitle,omitempty"`
	FromDate string `json:"fromDate,omitempty"`
	ToDate   string `json:"toDate,omitempty"`
	Comment  string `json:"comment,omitempty"`
}
