// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// TimeTotalDurationModel is the TimeTotalDurationModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TimeTotalDurationModel struct {
	Hours   int32  `json:"hours,omitempty"`
	Minutes string `json:"minutes,omitempty"`
	Label   string `json:"label,omitempty"`
}
