// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimEmployeeJobDetailModelEmployeeTerminationRecord is the PimEmployeeJobDetailModelEmployeeTerminationRecord schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimEmployeeJobDetailModelEmployeeTerminationRecord struct {
	Id   int32       `json:"id,omitempty"`
	Date LooseString `json:"date,omitempty"`
}
