// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// RecruitmentCandidateListModel is the RecruitmentCandidateListModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type RecruitmentCandidateListModel struct {
	Id                int32                                      `json:"id,omitempty"`
	FirstName         LooseString                                `json:"firstName,omitempty"`
	MiddleName        LooseString                                `json:"middleName,omitempty"`
	LastName          LooseString                                `json:"lastName,omitempty"`
	DateOfApplication LooseString                                `json:"dateOfApplication,omitempty"`
	Vacancy           *RecruitmentCandidateListModelVacancy      `json:"vacancy,omitempty"`
	Status            []RecruitmentCandidateListModelStatusInner `json:"status"`
	HasAttachment     bool                                       `json:"hasAttachment"`
	Deletable         bool                                       `json:"deletable"`
}
