// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyTimeAtWork200ResponseMetaLastAction is the GetMyTimeAtWork200ResponseMetaLastAction schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyTimeAtWork200ResponseMetaLastAction struct {
	State          string `json:"state,omitempty"`
	UtcDate        string `json:"utcDate,omitempty"`
	UtcTime        bool   `json:"utcTime"`
	UserDate       string `json:"userDate,omitempty"`
	UserTime       string `json:"userTime,omitempty"`
	TimezoneOffset bool   `json:"timezoneOffset"`
}
