// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PerformanceCompletedPerformanceReviewModel is the PerformanceCompletedPerformanceReviewModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PerformanceCompletedPerformanceReviewModel struct {
	Id                int32                                                   `json:"id,omitempty"`
	JobTitle          DashboardEmployeeOnLeaveListModelLeaveType              `json:"jobTitle,omitempty"`
	Subunit           ClaimEmployeeClaimRequestModelClaimEvent                `json:"subunit,omitempty"`
	ReviewPeriodStart float32                                                 `json:"reviewPeriodStart,omitempty"`
	ReviewPeriodEnd   float32                                                 `json:"reviewPeriodEnd,omitempty"`
	DueDate           float32                                                 `json:"dueDate,omitempty"`
	OverallStatus     PerformanceCompletedPerformanceReviewModelOverallStatus `json:"overallStatus,omitempty"`
	FinalRating       float32                                                 `json:"finalRating,omitempty"`
	FinalComment      string                                                  `json:"finalComment,omitempty"`
	CompletedDate     float32                                                 `json:"completedDate,omitempty"`
}
