// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesPersonalDetailsRequest is the UpdateAnEmployeesPersonalDetailsRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesPersonalDetailsRequest struct {
	LastName                  LooseString `json:"lastName,omitempty"`
	FirstName                 LooseString `json:"firstName,omitempty"`
	MiddleName                LooseString `json:"middleName,omitempty"`
	EmployeeId                LooseString `json:"employeeId,omitempty"`
	OtherId                   LooseString `json:"otherId,omitempty"`
	DrivingLicenseNo          LooseString `json:"drivingLicenseNo,omitempty"`
	DrivingLicenseExpiredDate LooseString `json:"drivingLicenseExpiredDate,omitempty"`
	SsnNumber                 LooseString `json:"ssnNumber,omitempty"`
	SinNumber                 LooseString `json:"sinNumber,omitempty"`
	Gender                    int32       `json:"gender,omitempty"`
	MaritalStatus             LooseString `json:"maritalStatus,omitempty"`
	Birthday                  LooseString `json:"birthday,omitempty"`
	NationalityId             int32       `json:"nationalityId,omitempty"`
	Nickname                  LooseString `json:"nickname,omitempty"`
	Smoker                    bool        `json:"smoker"`
	MilitaryService           LooseString `json:"militaryService,omitempty"`
}
