// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateALeaveRequestRequest is the CreateALeaveRequestRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateALeaveRequestRequest struct {
	EmpNumber     int32                               `json:"empNumber,omitempty"`
	LeaveTypeId   int32                               `json:"leaveTypeId,omitempty"`
	FromDate      LooseString                         `json:"fromDate,omitempty"`
	ToDate        LooseString                         `json:"toDate,omitempty"`
	Comment       LooseString                         `json:"comment,omitempty"`
	PartialOption LooseString                         `json:"partialOption,omitempty"`
	Duration      *CreateALeaveRequestRequestDuration `json:"duration,omitempty"`
}
