// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyTimeAtWork200ResponseMeta is the GetMyTimeAtWork200ResponseMeta schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyTimeAtWork200ResponseMeta struct {
	LastAction  GetMyTimeAtWork200ResponseMetaLastAction  `json:"lastAction,omitempty"`
	CurrentDay  GetMyTimeAtWork200ResponseMetaCurrentDay  `json:"currentDay,omitempty"`
	CurrentWeek GetMyTimeAtWork200ResponseMetaCurrentWeek `json:"currentWeek,omitempty"`
	CurrentUser GetMyTimeAtWork200ResponseMetaCurrentUser `json:"currentUser,omitempty"`
}
