// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetTimeReportData200ResponseDataInnerHeadersInner is the GetTimeReportData200ResponseDataInnerHeadersInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetTimeReportData200ResponseDataInnerHeadersInner struct {
	ActivityId   int32                                                 `json:"activityId,omitempty"`
	ActivityName string                                                `json:"activityName,omitempty"`
	Deleted      bool                                                  `json:"deleted"`
	Time         string                                                `json:"time,omitempty"`
	Url          *GetTimeReportData200ResponseDataInnerHeadersInnerUrl `json:"_url,omitempty"`
}
