// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AddAnAttachmentToACandidateRequest is the AddAnAttachmentToACandidateRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AddAnAttachmentToACandidateRequest struct {
	CandidateId int32             `json:"candidateId,omitempty"`
	Attachment  *Base64Attachment `json:"attachment,omitempty"`
}
