// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AddAnAttachmentToAVacancyRequest is the AddAnAttachmentToAVacancyRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AddAnAttachmentToAVacancyRequest struct {
	VacancyId      int32             `json:"vacancyId,omitempty"`
	Comment        LooseString       `json:"comment,omitempty"`
	AttachmentType int32             `json:"attachmentType,omitempty"`
	Attachment     *Base64Attachment `json:"attachment,omitempty"`
}
