// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyEligibleLeaveTypes200Response is the GetMyEligibleLeaveTypes200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyEligibleLeaveTypes200Response struct {
	Data *LeaveLeaveTypeModel                    `json:"data,omitempty"`
	Meta *GetMyEligibleLeaveTypes200ResponseMeta `json:"meta,omitempty"`
}
