// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllEmailSubscribers200Response is the ListAllEmailSubscribers200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllEmailSubscribers200Response struct {
	Data []AdminEmailSubscriberModel            `json:"data"`
	Meta ListAllEmailSubscribers200ResponseMeta `json:"meta,omitempty"`
}
