// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateAProjectRequest is the CreateAProjectRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateAProjectRequest struct {
	CustomerId              int32   `json:"customerId,omitempty"`
	Name                    string  `json:"name,omitempty"`
	Description             string  `json:"description,omitempty"`
	ProjectAdminsEmpNumbers []int32 `json:"projectAdminsEmpNumbers,omitempty"`
}
