// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AddASalaryComponentToAnEmployeeRequest is the AddASalaryComponentToAnEmployeeRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AddASalaryComponentToAnEmployeeRequest struct {
	PayGradeId                 int32       `json:"payGradeId,omitempty"`
	SalaryComponent            LooseString `json:"salaryComponent,omitempty"`
	PayFrequencyId             int32       `json:"payFrequencyId,omitempty"`
	CurrencyId                 LooseString `json:"currencyId,omitempty"`
	SalaryAmount               LooseString `json:"salaryAmount,omitempty"`
	Comment                    LooseString `json:"comment,omitempty"`
	AddDirectDeposit           bool        `json:"addDirectDeposit"`
	DirectDepositAccount       LooseString `json:"directDepositAccount,omitempty"`
	DirectDepositAccountType   LooseString `json:"directDepositAccountType,omitempty"`
	DirectDepositRoutingNumber LooseString `json:"directDepositRoutingNumber,omitempty"`
	DirectDepositAmount        float32     `json:"directDepositAmount,omitempty"`
}
