// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ClaimAttachmentModelAttachment is the ClaimAttachmentModelAttachment schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ClaimAttachmentModelAttachment struct {
	FileName        string `json:"fileName,omitempty"`
	FileType        string `json:"fileType,omitempty"`
	FileSize        int32  `json:"fileSize,omitempty"`
	FileDescription string `json:"fileDescription,omitempty"`
}
