// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetMyActionSummary200Response is the GetMyActionSummary200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetMyActionSummary200Response struct {
	Id                 int32       `json:"id,omitempty"`
	Group              LooseString `json:"group,omitempty"`
	PendingActionCount int32       `json:"pendingActionCount,omitempty"`
}
