// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ListAllPayGradeCurrencies200Response is the ListAllPayGradeCurrencies200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ListAllPayGradeCurrencies200Response struct {
	Data []AdminPayGradeCurrencyModel           `json:"data"`
	Meta ListAllEducationRecords200ResponseMeta `json:"meta,omitempty"`
}
