// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetATimesheetsEntries200ResponseMetaTimesheet is the GetATimesheetsEntries200ResponseMetaTimesheet schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetATimesheetsEntries200ResponseMetaTimesheet struct {
	Id        int32                                               `json:"id,omitempty"`
	Status    GetATimesheetsEntries200ResponseMetaTimesheetStatus `json:"status,omitempty"`
	StartDate string                                              `json:"startDate,omitempty"`
	EndDate   string                                              `json:"endDate,omitempty"`
}
