// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesPersonalDetailsRequest is the UpdateAnEmployeesPersonalDetailsRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesPersonalDetailsRequest struct {
	LastName                  string `json:"lastName,omitempty"`
	FirstName                 string `json:"firstName,omitempty"`
	MiddleName                string `json:"middleName,omitempty"`
	EmployeeId                string `json:"employeeId,omitempty"`
	OtherId                   string `json:"otherId,omitempty"`
	DrivingLicenseNo          string `json:"drivingLicenseNo,omitempty"`
	DrivingLicenseExpiredDate string `json:"drivingLicenseExpiredDate,omitempty"`
	SsnNumber                 string `json:"ssnNumber,omitempty"`
	SinNumber                 string `json:"sinNumber,omitempty"`
	Gender                    int32  `json:"gender,omitempty"`
	MaritalStatus             string `json:"maritalStatus,omitempty"`
	Birthday                  string `json:"birthday,omitempty"`
	NationalityId             int32  `json:"nationalityId,omitempty"`
	Nickname                  string `json:"nickname,omitempty"`
	Smoker                    bool   `json:"smoker"`
	MilitaryService           string `json:"militaryService,omitempty"`
}
