// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetAnEmployeeDirectoryListing200Response is the GetAnEmployeeDirectoryListing200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetAnEmployeeDirectoryListing200Response struct {
	Data []GetAnEmployeeDirectoryListing200ResponseDataInner `json:"data,omitempty"`
	Meta interface{}                                         `json:"meta,omitempty"`
}
