// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PimMyInfoDetailedModelJobTitle is the PimMyInfoDetailedModelJobTitle schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PimMyInfoDetailedModelJobTitle struct {
	Id        int32  `json:"id,omitempty"`
	Title     string `json:"title,omitempty"`
	IsDeleted bool   `json:"isDeleted,omitempty"`
}
