// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// GetLeaveReportData200Response is the GetLeaveReportData200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type GetLeaveReportData200Response struct {
	Data []GetLeaveReportData200ResponseDataInner `json:"data"`
	Meta GetLeaveReportData200ResponseMeta        `json:"meta,omitempty"`
}
