// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UnlikeALikedComment400ResponseError is the UnlikeALikedComment400ResponseError schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UnlikeALikedComment400ResponseError struct {
	Status   string `json:"status,omitempty"`
	Messsage string `json:"messsage,omitempty"`
}
