// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// PostTextPhotosOrVideo200ResponseDataInner is the PostTextPhotosOrVideo200ResponseDataInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type PostTextPhotosOrVideo200ResponseDataInner struct {
	Id           int32                                              `json:"id,omitempty"`
	Employee     *GetAnEmployeesClaimRequest200ResponseMetaEmployee `json:"employee,omitempty"`
	Post         *BuzzPostPhotoEditDeletedPhotosInner               `json:"post,omitempty"`
	Type         string                                             `json:"type,omitempty"`
	Liked        bool                                               `json:"liked"`
	Text         string                                             `json:"text,omitempty"`
	Stats        *BuzzFeedPostModelTextStats                        `json:"stats,omitempty"`
	CreatedDate  string                                             `json:"createdDate,omitempty"`
	CreatedTime  string                                             `json:"createdTime,omitempty"`
	OriginalPost *BuzzFeedPostModelShareOriginalPost                `json:"originalPost,omitempty"`
	Permission   *BuzzBuzzDetailedCommentModelPermission            `json:"permission,omitempty"`
	PhotoIds     []int32                                            `json:"photoIds"`
	Video        *BuzzFeedPostModelVideoVideo                       `json:"video,omitempty"`
}
