// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnEmployeesJobDetailsRequest is the UpdateAnEmployeesJobDetailsRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnEmployeesJobDetailsRequest struct {
	JoinedDate    LooseString `json:"joinedDate,omitempty"`
	JobTitleId    int32       `json:"jobTitleId,omitempty"`
	EmpStatusId   int32       `json:"empStatusId,omitempty"`
	JobCategoryId int32       `json:"jobCategoryId,omitempty"`
	SubunitId     int32       `json:"subunitId,omitempty"`
	LocationId    int32       `json:"locationId,omitempty"`
}
