// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAnAttendanceRecordRequest is the UpdateAnAttendanceRecordRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAnAttendanceRecordRequest struct {
	PunchInDate          string  `json:"punchInDate,omitempty"`
	PunchInTime          string  `json:"punchInTime,omitempty"`
	PunchInOffset        float32 `json:"punchInOffset,omitempty"`
	PunchInTimezoneName  string  `json:"punchInTimezoneName,omitempty"`
	PunchOutDate         string  `json:"punchOutDate,omitempty"`
	PunchOutTime         string  `json:"punchOutTime,omitempty"`
	PunchOutOffset       float32 `json:"punchOutOffset,omitempty"`
	PunchOutTimezoneName string  `json:"punchOutTimezoneName,omitempty"`
	PunchOutNote         string  `json:"punchOutNote,omitempty"`
}
