// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// LeaveLeaveRequestDetailedModel is the LeaveLeaveRequestDetailedModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LeaveLeaveRequestDetailedModel struct {
	Id                int32                                                     `json:"id,omitempty"`
	Dates             LeaveLeaveRequestDetailedModelDates                       `json:"dates,omitempty"`
	NoOfDays          int32                                                     `json:"noOfDays,omitempty"`
	LeaveBalances     []LeaveLeaveRequestDetailedModelLeaveBalancesInner        `json:"leaveBalances,omitempty"`
	MultiPeriod       bool                                                      `json:"multiPeriod,omitempty"`
	LeaveBreakdown    LeaveLeaveRequestDetailedModelLeaveBreakdown              `json:"leaveBreakdown,omitempty"`
	AllowedActions    []GetATimesheetsEntries200ResponseMetaAllowedActionsInner `json:"allowedActions,omitempty"`
	HasMultipleStatus bool                                                      `json:"hasMultipleStatus,omitempty"`
	Employee          GetAnEmployeesClaimRequest200ResponseMetaEmployee         `json:"employee,omitempty"`
	LeaveType         DashboardEmployeeOnLeaveListModelLeaveType                `json:"leaveType,omitempty"`
	LastComment       LeaveLeaveRequestDetailedModelLastComment                 `json:"lastComment,omitempty"`
}
