// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// CreateWorkspaceNotificationRegistrationRequest is the CreateWorkspaceNotificationRegistrationRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CreateWorkspaceNotificationRegistrationRequest struct {
	EventType     string  `json:"eventType,omitempty"`
	Provider      string  `json:"provider,omitempty"`
	WebhookUrl    string  `json:"webhookUrl,omitempty"`
	ChannelLabel  string  `json:"channelLabel,omitempty"`
	SubunitIds    []int32 `json:"subunitIds"`
	Timezone      string  `json:"timezone,omitempty"`
	DailySendTime string  `json:"dailySendTime,omitempty"`
	Active        bool    `json:"active"`
}
