// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// AdminI18NImportErrorModelError is the AdminI18NImportErrorModelError schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type AdminI18NImportErrorModelError struct {
	Code    string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
