// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// UpdateAJobTitleRequest is the UpdateAJobTitleRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type UpdateAJobTitleRequest struct {
	Title                   string                  `json:"title,omitempty"`
	Description             string                  `json:"description,omitempty"`
	Note                    string                  `json:"note,omitempty"`
	CurrentJobSpecification string                  `json:"currentJobSpecification,omitempty"`
	Specification           *Base64AttachmentOrNull `json:"specification,omitempty"`
}
