// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package orangehrm

// ClaimRequestModel is the ClaimRequestModel schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ClaimRequestModel struct {
	Id          int32                         `json:"id,omitempty"`
	ReferenceId LooseString                   `json:"referenceId,omitempty"`
	ClaimEvent  *ClaimExpenseModelExpenseType `json:"claimEvent,omitempty"`
	Currency    *ClaimRequestModelCurrency    `json:"currency,omitempty"`
	Description LooseString                   `json:"description,omitempty"`
	Status      LooseString                   `json:"status,omitempty"`
}
