// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &TimeProjectActivitiesCopy{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// TimeProjectActivitiesCopyParameters are the configurable fields of a TimeProjectActivitiesCopy.
//
// These are the fields of the create request body (), which is
// exactly what a person may write. Anything the server assigns is in
// TimeProjectActivitiesCopyObservation instead.
type TimeProjectActivitiesCopyParameters struct {
	// ToProjectId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="toProjectId is immutable"
	ToProjectId string `json:"toProjectId"`
}

// TimeProjectActivitiesCopyObservation are the observable fields of a TimeProjectActivitiesCopy.
//
// These are the fields of the read response (TimeCopyActivityModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type TimeProjectActivitiesCopyObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Unique
	Unique bool `json:"unique,omitempty"`
}

// A TimeProjectActivitiesCopySpec defines the desired state of a TimeProjectActivitiesCopy.
type TimeProjectActivitiesCopySpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              TimeProjectActivitiesCopyParameters `json:"forProvider"`
}

// A TimeProjectActivitiesCopyStatus represents the observed state of a TimeProjectActivitiesCopy.
type TimeProjectActivitiesCopyStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 TimeProjectActivitiesCopyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A TimeProjectActivitiesCopy is a managed OrangeHRM timeProjectActivitiesCopy.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type TimeProjectActivitiesCopy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   TimeProjectActivitiesCopySpec   `json:"spec"`
	Status TimeProjectActivitiesCopyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TimeProjectActivitiesCopyList contains a list of TimeProjectActivitiesCopy
type TimeProjectActivitiesCopyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TimeProjectActivitiesCopy `json:"items"`
}

// TimeProjectActivitiesCopy type metadata.
var (
	TimeProjectActivitiesCopyKind             = reflect.TypeOf(TimeProjectActivitiesCopy{}).Name()
	TimeProjectActivitiesCopyGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TimeProjectActivitiesCopyKind}.String()
	TimeProjectActivitiesCopyKindAPIVersion   = TimeProjectActivitiesCopyKind + "." + SchemeGroupVersion.String()
	TimeProjectActivitiesCopyGroupVersionKind = SchemeGroupVersion.WithKind(TimeProjectActivitiesCopyKind)
)

func init() {
	SchemeBuilder.Register(&TimeProjectActivitiesCopy{}, &TimeProjectActivitiesCopyList{})
}
