//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembership) DeepCopyInto(out *PimEmployeeMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembership.
func (in *PimEmployeeMembership) DeepCopy() *PimEmployeeMembership {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembershipList) DeepCopyInto(out *PimEmployeeMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimEmployeeMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembershipList.
func (in *PimEmployeeMembershipList) DeepCopy() *PimEmployeeMembershipList {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembershipObservation) DeepCopyInto(out *PimEmployeeMembershipObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembershipObservation.
func (in *PimEmployeeMembershipObservation) DeepCopy() *PimEmployeeMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembershipParameters) DeepCopyInto(out *PimEmployeeMembershipParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembershipParameters.
func (in *PimEmployeeMembershipParameters) DeepCopy() *PimEmployeeMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembershipSpec) DeepCopyInto(out *PimEmployeeMembershipSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembershipSpec.
func (in *PimEmployeeMembershipSpec) DeepCopy() *PimEmployeeMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeMembershipStatus) DeepCopyInto(out *PimEmployeeMembershipStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeMembershipStatus.
func (in *PimEmployeeMembershipStatus) DeepCopy() *PimEmployeeMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
