// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &ClaimRequestExpense{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// ClaimRequestExpenseParameters are the configurable fields of a ClaimRequestExpense.
//
// These are the fields of the create request body (AddAnExpenseToAClaimRequest), which is
// exactly what a person may write. Anything the server assigns is in
// ClaimRequestExpenseObservation instead.
type ClaimRequestExpenseParameters struct {
	// RequestId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="requestId is immutable"
	RequestId string `json:"requestId"`

	// ExpenseTypeId
	// +kubebuilder:validation:Required
	ExpenseTypeId int64 `json:"expenseTypeId"`

	// Amount
	// +kubebuilder:validation:Required
	Amount float64 `json:"amount"`

	// Note
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Note string `json:"note,omitempty"`

	// Date
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Date string `json:"date"`
}

// ClaimRequestExpenseObservation are the observable fields of a ClaimRequestExpense.
//
// These are the fields of the read response (ClaimExpenseModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type ClaimRequestExpenseObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// ClaimRequest
	ClaimRequest string `json:"claimRequest,omitempty"`

	// ExpenseType
	ExpenseType string `json:"expenseType,omitempty"`

	// Amount
	Amount float64 `json:"amount,omitempty"`

	// Note
	Note string `json:"note,omitempty"`
}

// A ClaimRequestExpenseSpec defines the desired state of a ClaimRequestExpense.
type ClaimRequestExpenseSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              ClaimRequestExpenseParameters `json:"forProvider"`
}

// A ClaimRequestExpenseStatus represents the observed state of a ClaimRequestExpense.
type ClaimRequestExpenseStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 ClaimRequestExpenseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A ClaimRequestExpense is a managed OrangeHRM claimRequestExpense.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type ClaimRequestExpense struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClaimRequestExpenseSpec   `json:"spec"`
	Status ClaimRequestExpenseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClaimRequestExpenseList contains a list of ClaimRequestExpense
type ClaimRequestExpenseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClaimRequestExpense `json:"items"`
}

// ClaimRequestExpense type metadata.
var (
	ClaimRequestExpenseKind             = reflect.TypeOf(ClaimRequestExpense{}).Name()
	ClaimRequestExpenseGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClaimRequestExpenseKind}.String()
	ClaimRequestExpenseKindAPIVersion   = ClaimRequestExpenseKind + "." + SchemeGroupVersion.String()
	ClaimRequestExpenseGroupVersionKind = SchemeGroupVersion.WithKind(ClaimRequestExpenseKind)
)

func init() {
	SchemeBuilder.Register(&ClaimRequestExpense{}, &ClaimRequestExpenseList{})
}
