// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package controller

import (
	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	ctrl "sigs.k8s.io/controller-runtime"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/config"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_education"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_email_subscription_subscriber"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_employment_status"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_i18n_language"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_job_category"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_job_title"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_language"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_license"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_location"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_membership"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_nationality"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_oauth_client"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_pay_grade"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_pay_grade_currency"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_skill"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_subunit"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_user"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_work_shift"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/admin_workspace_notification_registration"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/attendance_employee_record"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/attendance_record"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/auth_openid_provider"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/buzz_comment_like"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/buzz_post"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/buzz_share"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/buzz_share_comment"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/buzz_share_like"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_employee_request"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_event"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_expenses_type"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_request"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_request_attachment"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/claim_request_expense"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/leave_employees_leave_request"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/leave_holiday"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/leave_leave_entitlement"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/leave_leave_request"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/leave_leave_type"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/performance_config_tracker"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/performance_employees_tracker"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/performance_kpi"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/performance_manage_review"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/performance_tracker_log"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_custom_field"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_dependent"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_education"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_emergency_contact"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_immigration"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_language"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_language_fluency"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_license"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_membership"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_salary_component"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_screen_attachment"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_skill"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_subordinate"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_supervisor"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_termination"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_employee_work_experience"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_reporting_method"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_reports_defined"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/pim_termination_reason"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_candidate"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_candidate_history"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_candidate_interview"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_interview_attachment"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_vacancy"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/recruitment_vacancy_attachment"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/time_customer"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/time_project_activity"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/time_project"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/time_project_activities_copy"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/controller/time_validation_activity_name"
)

// SetupGated creates all OrangeHRM controllers with safe-start support and adds
// them to the supplied manager.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	for _, setup := range []func(ctrl.Manager, controller.Options) error{
		config.Setup,

		admin_education.SetupGated,

		admin_email_subscription_subscriber.SetupGated,

		admin_employment_status.SetupGated,

		admin_i18n_language.SetupGated,

		admin_job_category.SetupGated,

		admin_job_title.SetupGated,

		admin_language.SetupGated,

		admin_license.SetupGated,

		admin_location.SetupGated,

		admin_membership.SetupGated,

		admin_nationality.SetupGated,

		admin_oauth_client.SetupGated,

		admin_pay_grade.SetupGated,

		admin_pay_grade_currency.SetupGated,

		admin_skill.SetupGated,

		admin_subunit.SetupGated,

		admin_user.SetupGated,

		admin_work_shift.SetupGated,

		admin_workspace_notification_registration.SetupGated,

		attendance_employee_record.SetupGated,

		attendance_record.SetupGated,

		auth_openid_provider.SetupGated,

		buzz_comment_like.SetupGated,

		buzz_post.SetupGated,

		buzz_share.SetupGated,

		buzz_share_comment.SetupGated,

		buzz_share_like.SetupGated,

		claim_employee_request.SetupGated,

		claim_event.SetupGated,

		claim_expenses_type.SetupGated,

		claim_request.SetupGated,

		claim_request_attachment.SetupGated,

		claim_request_expense.SetupGated,

		leave_employees_leave_request.SetupGated,

		leave_holiday.SetupGated,

		leave_leave_entitlement.SetupGated,

		leave_leave_request.SetupGated,

		leave_leave_type.SetupGated,

		performance_config_tracker.SetupGated,

		performance_employees_tracker.SetupGated,

		performance_kpi.SetupGated,

		performance_manage_review.SetupGated,

		performance_tracker_log.SetupGated,

		pim_custom_field.SetupGated,

		pim_employee.SetupGated,

		pim_employee_dependent.SetupGated,

		pim_employee_education.SetupGated,

		pim_employee_emergency_contact.SetupGated,

		pim_employee_immigration.SetupGated,

		pim_employee_language.SetupGated,

		pim_employee_language_fluency.SetupGated,

		pim_employee_license.SetupGated,

		pim_employee_membership.SetupGated,

		pim_employee_salary_component.SetupGated,

		pim_employee_screen_attachment.SetupGated,

		pim_employee_skill.SetupGated,

		pim_employee_subordinate.SetupGated,

		pim_employee_supervisor.SetupGated,

		pim_employee_termination.SetupGated,

		pim_employee_work_experience.SetupGated,

		pim_reporting_method.SetupGated,

		pim_reports_defined.SetupGated,

		pim_termination_reason.SetupGated,

		recruitment_candidate.SetupGated,

		recruitment_candidate_history.SetupGated,

		recruitment_candidate_interview.SetupGated,

		recruitment_interview_attachment.SetupGated,

		recruitment_vacancy.SetupGated,

		recruitment_vacancy_attachment.SetupGated,

		time_customer.SetupGated,

		time_project_activity.SetupGated,

		time_project.SetupGated,

		time_project_activities_copy.SetupGated,

		time_validation_activity_name.SetupGated,
	} {
		if err := setup(mgr, o); err != nil {
			return err
		}
	}
	return nil
}
