// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &BuzzCommentLike{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// BuzzCommentLikeParameters are the configurable fields of a BuzzCommentLike.
//
// These are the fields of the create request body (), which is
// exactly what a person may write. Anything the server assigns is in
// BuzzCommentLikeObservation instead.
type BuzzCommentLikeParameters struct {
	// CommentId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="commentId is immutable"
	CommentId string `json:"commentId"`
}

// BuzzCommentLikeObservation are the observable fields of a BuzzCommentLike.
//
// These are the fields of the read response (BuzzBuzzLikeOnCommentModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type BuzzCommentLikeObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// LikedAtDate
	LikedAtDate string `json:"likedAtDate,omitempty"`

	// LikedAtTime
	LikedAtTime string `json:"likedAtTime,omitempty"`

	// Comment
	Comment string `json:"comment,omitempty"`

	// Employee
	Employee string `json:"employee,omitempty"`
}

// A BuzzCommentLikeSpec defines the desired state of a BuzzCommentLike.
type BuzzCommentLikeSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              BuzzCommentLikeParameters `json:"forProvider"`
}

// A BuzzCommentLikeStatus represents the observed state of a BuzzCommentLike.
type BuzzCommentLikeStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 BuzzCommentLikeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A BuzzCommentLike is a managed OrangeHRM buzzCommentLike.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type BuzzCommentLike struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   BuzzCommentLikeSpec   `json:"spec"`
	Status BuzzCommentLikeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BuzzCommentLikeList contains a list of BuzzCommentLike
type BuzzCommentLikeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BuzzCommentLike `json:"items"`
}

// BuzzCommentLike type metadata.
var (
	BuzzCommentLikeKind             = reflect.TypeOf(BuzzCommentLike{}).Name()
	BuzzCommentLikeGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BuzzCommentLikeKind}.String()
	BuzzCommentLikeKindAPIVersion   = BuzzCommentLikeKind + "." + SchemeGroupVersion.String()
	BuzzCommentLikeGroupVersionKind = SchemeGroupVersion.WithKind(BuzzCommentLikeKind)
)

func init() {
	SchemeBuilder.Register(&BuzzCommentLike{}, &BuzzCommentLikeList{})
}
