// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &RecruitmentVacancyAttachment{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// RecruitmentVacancyAttachmentParameters are the configurable fields of a RecruitmentVacancyAttachment.
//
// These are the fields of the create request body (AddAnAttachmentToAVacancyRequest), which is
// exactly what a person may write. Anything the server assigns is in
// RecruitmentVacancyAttachmentObservation instead.
type RecruitmentVacancyAttachmentParameters struct {
	// VacancyId
	// +kubebuilder:validation:Required
	VacancyId int64 `json:"vacancyId"`

	// Comment
	// +optional
	Comment string `json:"comment,omitempty"`

	// AttachmentType
	// +optional
	AttachmentType int64 `json:"attachmentType,omitempty"`

	// Attachment
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Attachment string `json:"attachment"`
}

// RecruitmentVacancyAttachmentObservation are the observable fields of a RecruitmentVacancyAttachment.
//
// These are the fields of the read response (RecruitmentVacancyAttachmentModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type RecruitmentVacancyAttachmentObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// VacancyId
	VacancyId int64 `json:"vacancyId,omitempty"`

	// Attachment
	Attachment string `json:"attachment,omitempty"`

	// Comment
	Comment string `json:"comment,omitempty"`
}

// A RecruitmentVacancyAttachmentSpec defines the desired state of a RecruitmentVacancyAttachment.
type RecruitmentVacancyAttachmentSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              RecruitmentVacancyAttachmentParameters `json:"forProvider"`
}

// A RecruitmentVacancyAttachmentStatus represents the observed state of a RecruitmentVacancyAttachment.
type RecruitmentVacancyAttachmentStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 RecruitmentVacancyAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A RecruitmentVacancyAttachment is a managed OrangeHRM recruitmentVacancyAttachment.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type RecruitmentVacancyAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RecruitmentVacancyAttachmentSpec   `json:"spec"`
	Status RecruitmentVacancyAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecruitmentVacancyAttachmentList contains a list of RecruitmentVacancyAttachment
type RecruitmentVacancyAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RecruitmentVacancyAttachment `json:"items"`
}

// RecruitmentVacancyAttachment type metadata.
var (
	RecruitmentVacancyAttachmentKind             = reflect.TypeOf(RecruitmentVacancyAttachment{}).Name()
	RecruitmentVacancyAttachmentGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RecruitmentVacancyAttachmentKind}.String()
	RecruitmentVacancyAttachmentKindAPIVersion   = RecruitmentVacancyAttachmentKind + "." + SchemeGroupVersion.String()
	RecruitmentVacancyAttachmentGroupVersionKind = SchemeGroupVersion.WithKind(RecruitmentVacancyAttachmentKind)
)

func init() {
	SchemeBuilder.Register(&RecruitmentVacancyAttachment{}, &RecruitmentVacancyAttachmentList{})
}
