// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeTermination{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeTerminationParameters are the configurable fields of a PimEmployeeTermination.
//
// These are the fields of the create request body (TerminateAnEmployeeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeTerminationObservation instead.
type PimEmployeeTerminationParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// TerminationReasonId
	// +kubebuilder:validation:Required
	TerminationReasonId int64 `json:"terminationReasonId"`

	// Date
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Date string `json:"date"`

	// Note
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Note string `json:"note,omitempty"`
}

// PimEmployeeTerminationObservation are the observable fields of a PimEmployeeTermination.
//
// These are the fields of the read response (PimEmployeeTerminationModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeTerminationObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Note
	Note string `json:"note,omitempty"`

	// Date
	Date string `json:"date,omitempty"`

	// TerminationReason
	TerminationReason string `json:"terminationReason,omitempty"`
}

// A PimEmployeeTerminationSpec defines the desired state of a PimEmployeeTermination.
type PimEmployeeTerminationSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeTerminationParameters `json:"forProvider"`
}

// A PimEmployeeTerminationStatus represents the observed state of a PimEmployeeTermination.
type PimEmployeeTerminationStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeTerminationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeTermination is a managed OrangeHRM pimEmployeeTermination.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeTermination struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeTerminationSpec   `json:"spec"`
	Status PimEmployeeTerminationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeTerminationList contains a list of PimEmployeeTermination
type PimEmployeeTerminationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeTermination `json:"items"`
}

// PimEmployeeTermination type metadata.
var (
	PimEmployeeTerminationKind             = reflect.TypeOf(PimEmployeeTermination{}).Name()
	PimEmployeeTerminationGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeTerminationKind}.String()
	PimEmployeeTerminationKindAPIVersion   = PimEmployeeTerminationKind + "." + SchemeGroupVersion.String()
	PimEmployeeTerminationGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeTerminationKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeTermination{}, &PimEmployeeTerminationList{})
}
