// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AdminJobTitle{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AdminJobTitleParameters are the configurable fields of a AdminJobTitle.
//
// These are the fields of the create request body (CreateAJobTitleRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AdminJobTitleObservation instead.
type AdminJobTitleParameters struct {
	// Title
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Title string `json:"title"`

	// Description
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Description string `json:"description,omitempty"`

	// Note
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Note string `json:"note,omitempty"`

	// Specification
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Specification string `json:"specification,omitempty"`
}

// AdminJobTitleObservation are the observable fields of a AdminJobTitle.
//
// These are the fields of the read response (AdminJobTitleModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AdminJobTitleObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Title
	Title string `json:"title,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// Note
	Note string `json:"note,omitempty"`

	// JobSpecification
	JobSpecification string `json:"jobSpecification,omitempty"`
}

// A AdminJobTitleSpec defines the desired state of a AdminJobTitle.
type AdminJobTitleSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AdminJobTitleParameters `json:"forProvider"`
}

// A AdminJobTitleStatus represents the observed state of a AdminJobTitle.
type AdminJobTitleStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AdminJobTitleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AdminJobTitle is a managed OrangeHRM adminJobTitle.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AdminJobTitle struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AdminJobTitleSpec   `json:"spec"`
	Status AdminJobTitleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdminJobTitleList contains a list of AdminJobTitle
type AdminJobTitleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdminJobTitle `json:"items"`
}

// AdminJobTitle type metadata.
var (
	AdminJobTitleKind             = reflect.TypeOf(AdminJobTitle{}).Name()
	AdminJobTitleGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdminJobTitleKind}.String()
	AdminJobTitleKindAPIVersion   = AdminJobTitleKind + "." + SchemeGroupVersion.String()
	AdminJobTitleGroupVersionKind = SchemeGroupVersion.WithKind(AdminJobTitleKind)
)

func init() {
	SchemeBuilder.Register(&AdminJobTitle{}, &AdminJobTitleList{})
}
