// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package leave_leave_request

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/ratelimiter"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/apis/leave_leave_request/v1alpha1"
	apisv1alpha1 "github.com/n-at-han-k/crossplane-provider-orangehrm/apis/v1alpha1"
	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/clients/orangehrm"
)

const (
	errTrackPCUsage = "cannot track ProviderConfig usage"
	errGetPC        = "cannot get ProviderConfig"
	errGetCPC       = "cannot get ClusterProviderConfig"
	errGetCreds     = "cannot get credentials"
	errNewClient    = "cannot create new Service"

	errGet    = "cannot get OrangeHRM leaveLeaveRequest"
	errCreate = "cannot create OrangeHRM leaveLeaveRequest"
	errUpdate = "cannot update OrangeHRM leaveLeaveRequest"
	errDelete = "cannot delete OrangeHRM leaveLeaveRequest"
	errParams = "cannot build the OrangeHRM leaveLeaveRequest request body"
	errParse  = "cannot parse the OrangeHRM leaveLeaveRequest response"

	// errNoID guards the one failure mode that silently leaks a resource: the
	// create succeeds but nothing in the answer carries an identifier. Setting
	// an empty external name would make every later Observe report
	// ResourceExists: false and create another one, forever.
	errNoID = "OrangeHRM returned no leaveLeaveRequest identifier from create; refusing to record an empty external name (one may have been created and needs manual cleanup)"
)

// newService builds the API client from the extracted credentials and the
// endpoint the ProviderConfig carries. The endpoint is NOT in the secret: it is
// not a secret, and keeping it out is what lets a ProviderConfig point straight
// at a Secret holding nothing but the token.
var newService = func(creds []byte, endpoint string) (*orangehrm.Client, error) {
	return orangehrm.NewClientFromCredentials(creds, endpoint)
}

// SetupGated adds a controller that reconciles LeaveLeaveRequest managed resources with safe-start support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			panic(errors.Wrap(err, "cannot setup LeaveLeaveRequest controller"))
		}
	}, v1alpha1.LeaveLeaveRequestGroupVersionKind)
	return nil
}

// Setup adds a controller that reconciles LeaveLeaveRequest managed resources.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.LeaveLeaveRequestGroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*v1alpha1.LeaveLeaveRequest](&connector{
			kube:         mgr.GetClient(),
			usage:        resource.NewProviderConfigUsageTracker(mgr.GetClient(), &apisv1alpha1.ProviderConfigUsage{}),
			newServiceFn: newService,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))), //nolint:staticcheck // Crossplane has not moved to the new events API yet.
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}

	if o.Features.Enabled(feature.EnableAlphaChangeLogs) {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}

	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
	}

	if o.MetricOptions != nil && o.MetricOptions.MRStateMetrics != nil {
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.LeaveLeaveRequestList{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind v1alpha1.LeaveLeaveRequestList")
		}
	}

	r := managed.NewReconciler(mgr, resource.ManagedKind(v1alpha1.LeaveLeaveRequestGroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(resource.DesiredStateChanged()).
		For(&v1alpha1.LeaveLeaveRequest{}).
		Complete(ratelimiter.NewReconciler(name, r, o.GlobalRateLimiter))
}

type connector struct {
	kube         client.Client
	usage        *resource.ProviderConfigUsageTracker
	newServiceFn func(creds []byte, endpoint string) (*orangehrm.Client, error)
}

// Connect tracks the ProviderConfig usage, reads the (Cluster)ProviderConfig
// the resource names, extracts its credentials and forms a client from them.
func (c *connector) Connect(ctx context.Context, cr *v1alpha1.LeaveLeaveRequest) (managed.TypedExternalClient[*v1alpha1.LeaveLeaveRequest], error) {
	if err := c.usage.Track(ctx, cr); err != nil {
		return nil, errors.Wrap(err, errTrackPCUsage)
	}

	var cd apisv1alpha1.ProviderCredentials
	var endpoint string

	ref := cr.GetProviderConfigReference()

	switch ref.Kind {
	case "ProviderConfig":
		pc := &apisv1alpha1.ProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: cr.GetNamespace()}, pc); err != nil {
			return nil, errors.Wrap(err, errGetPC)
		}
		cd = pc.Spec.Credentials
		endpoint = pc.Spec.Endpoint
	case "ClusterProviderConfig":
		cpc := &apisv1alpha1.ClusterProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name}, cpc); err != nil {
			return nil, errors.Wrap(err, errGetCPC)
		}
		cd = cpc.Spec.Credentials
		endpoint = cpc.Spec.Endpoint
	default:
		return nil, errors.Errorf("unsupported provider config kind: %s", ref.Kind)
	}

	data, err := resource.CommonCredentialExtractor(ctx, cd.Source, c.kube, cd.CommonCredentialSelectors)
	if err != nil {
		return nil, errors.Wrap(err, errGetCreds)
	}

	svc, err := c.newServiceFn(data, endpoint)
	if err != nil {
		return nil, errors.Wrap(err, errNewClient)
	}

	return &external{service: svc}, nil
}

type external struct {
	service *orangehrm.Client
}

// desired projects spec.forProvider onto the create request body. The JSON
// fields are strings in the CRD and real values on the wire, so they are
// unmarshalled here rather than passed through.
func desired(cr *v1alpha1.LeaveLeaveRequest) (*orangehrm.ApplyForLeaveRequest, error) {
	body := &orangehrm.ApplyForLeaveRequest{}

	body.Comment = cr.Spec.ForProvider.Comment
	if cr.Spec.ForProvider.Duration != "" {
		if err := json.Unmarshal([]byte(cr.Spec.ForProvider.Duration), &body.Duration); err != nil {
			return nil, errors.Wrap(err, "duration")
		}
	}
	if cr.Spec.ForProvider.EndDuration != "" {
		if err := json.Unmarshal([]byte(cr.Spec.ForProvider.EndDuration), &body.EndDuration); err != nil {
			return nil, errors.Wrap(err, "endDuration")
		}
	}
	body.PartialOption = cr.Spec.ForProvider.PartialOption
	body.FromDate = cr.Spec.ForProvider.FromDate
	body.ToDate = cr.Spec.ForProvider.ToDate
	body.LeaveTypeId = int32(cr.Spec.ForProvider.LeaveTypeId)

	return body, nil
}

// observation projects the read response onto status.atProvider.
func observation(in *orangehrm.GetMyLeaveRequest200ResponseData) (v1alpha1.LeaveLeaveRequestObservation, error) {
	out := v1alpha1.LeaveLeaveRequestObservation{}

	out.Id = int64(in.Id)
	if raw, err := json.Marshal(in.Dates); err == nil {
		out.Dates = string(raw)
	} else {
		return out, errors.Wrap(err, "dates")
	}
	out.NoOfDays = int64(in.NoOfDays)
	if raw, err := json.Marshal(in.LeaveBalances); err == nil {
		out.LeaveBalances = string(raw)
	} else {
		return out, errors.Wrap(err, "leaveBalances")
	}
	out.MultiPeriod = in.MultiPeriod
	if raw, err := json.Marshal(in.LeaveBreakdown); err == nil {
		out.LeaveBreakdown = string(raw)
	} else {
		return out, errors.Wrap(err, "leaveBreakdown")
	}
	if raw, err := json.Marshal(in.AllowedActions); err == nil {
		out.AllowedActions = string(raw)
	} else {
		return out, errors.Wrap(err, "allowedActions")
	}
	out.HasMultipleStatus = in.HasMultipleStatus
	if raw, err := json.Marshal(in.Employee); err == nil {
		out.Employee = string(raw)
	} else {
		return out, errors.Wrap(err, "employee")
	}
	if raw, err := json.Marshal(in.LeaveType); err == nil {
		out.LeaveType = string(raw)
	} else {
		return out, errors.Wrap(err, "leaveType")
	}
	if raw, err := json.Marshal(in.LastComment); err == nil {
		out.LastComment = string(raw)
	} else {
		return out, errors.Wrap(err, "lastComment")
	}
	out.DateApplied = float64(in.DateApplied)

	return out, nil
}

// upToDate compares only the fields the server answers under the same name
// and the same shape. A field it does not echo back -- a password, a body the
// server reshapes on the way out -- cannot be diffed without reporting drift
// on every reconcile, so it is left alone.
func upToDate(cr *v1alpha1.LeaveLeaveRequest, observed *orangehrm.GetMyLeaveRequest200ResponseData) bool {

	return true
}

// jsonEqual compares two JSON documents by value rather than by text, so that
// a server re-ordering an object's keys is not a permanent diff.
func jsonEqual(a, b string) bool {
	var left, right any

	if err := json.Unmarshal([]byte(a), &left); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(b), &right); err != nil {
		return false
	}

	x, err := json.Marshal(left)
	if err != nil {
		return false
	}
	y, err := json.Marshal(right)
	if err != nil {
		return false
	}

	return string(x) == string(y)
}

func (c *external) Observe(ctx context.Context, cr *v1alpha1.LeaveLeaveRequest) (managed.ExternalObservation, error) {
	// An external name that is not an id is the one crossplane-runtime seeded
	// from the resource's own Kubernetes name, so nothing has been created yet
	// (see IsID: asking for it would be a 422, which is not a 404).
	id := meta.GetExternalName(cr)
	if !orangehrm.IsID(id) {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	body, err := c.service.DoRequest(ctx, "GET", fmt.Sprintf("/api/v2/leave/leave-requests/%v", id), nil)
	if err != nil {
		// ONLY a 404 means it is gone. Any other failure (500, timeout,
		// throttling) must be surfaced -- treating it as "does not exist"
		// would provision a second one and orphan the first.
		if orangehrm.IsNotFound(err) {
			return managed.ExternalObservation{ResourceExists: false}, nil
		}
		return managed.ExternalObservation{}, errors.Wrap(err, errGet)
	}

	// Every OrangeHRM answer is an envelope -- {"data": …, "meta": …} -- and
	// what the resource IS is the data. The envelope itself is paging.
	var envelope orangehrm.GetMyLeaveRequest200Response
	if err := json.Unmarshal(body, &envelope); err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errParse)
	}
	// A pointer, because a struct field is one (see the generator): an answer
	// carrying no data at all is not something to project onto status.
	observed := envelope.Data
	if observed == nil {
		return managed.ExternalObservation{}, errors.New(errParse)
	}

	at, err := observation(observed)
	if err != nil {
		return managed.ExternalObservation{}, errors.Wrap(err, errParse)
	}
	cr.Status.AtProvider = at

	if meta.WasDeleted(cr) {
		cr.Status.SetConditions(xpv2.Deleting())
	} else {
		cr.Status.SetConditions(xpv2.Available())
	}

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: upToDate(cr, observed),
	}, nil
}

func (c *external) Create(ctx context.Context, cr *v1alpha1.LeaveLeaveRequest) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errParams)
	}

	respBody, location, err := c.service.DoCreateRequest(ctx, "POST", "/api/v2/leave/leave-requests", body)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
	}

	id := ""

	if len(respBody) == 0 {
		id = orangehrm.IDFromLocation(location)
	} else {
		var envelope orangehrm.GetMyLeaveRequest200Response
		if err := json.Unmarshal(respBody, &envelope); err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		created := envelope.Data
		if created == nil {
			return managed.ExternalCreation{}, errors.New(errParse)
		}
		// Through %v because OrangeHRM numbers its ids and an external name is
		// a string -- the annotation has to hold what the member path spells.
		id = fmt.Sprintf("%v", created.Id)

		at, err := observation(created)
		if err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		cr.Status.AtProvider = at
	}

	if id == "" {
		return managed.ExternalCreation{}, errors.New(errNoID)
	}

	meta.SetExternalName(cr, id)

	return managed.ExternalCreation{}, nil
}

func (c *external) Update(ctx context.Context, cr *v1alpha1.LeaveLeaveRequest) (managed.ExternalUpdate, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		return managed.ExternalUpdate{}, errors.New(errUpdate)
	}

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errParams)
	}

	respBody, err := c.service.DoRequest(ctx, "PUT", fmt.Sprintf("/api/v2/leave/leave-requests/%v", id), body)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errUpdate)
	}

	// The update's answer is not read: the next Observe reports the new state,
	// which is where status.atProvider comes from anyway, and a PUT that
	// answers something other than the record -- a bulk endpoint answering a
	// count -- would fail to parse on every successful update.
	_ = respBody

	return managed.ExternalUpdate{}, nil
}

func (c *external) Delete(ctx context.Context, cr *v1alpha1.LeaveLeaveRequest) (managed.ExternalDelete, error) {
	// This API offers no delete for a leaveLeaveRequest. Erroring rather than
	// returning success, because success would let Crossplane remove the
	// finalizer and forget a leaveLeaveRequest that still exists.
	return managed.ExternalDelete{}, errors.New("this API offers no delete for a leaveLeaveRequest; it must be removed out of band")
}

func (c *external) Disconnect(_ context.Context) error {
	return nil
}
