// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeLanguage{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeLanguageParameters are the configurable fields of a PimEmployeeLanguage.
//
// These are the fields of the create request body (AddALanguageToAnEmployeeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeLanguageObservation instead.
type PimEmployeeLanguageParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// LanguageId Specify the numerical ID of the language
	// +kubebuilder:validation:Required
	LanguageId int64 `json:"languageId"`

	// FluencyId Specify the numerical ID of the fluency
	// +kubebuilder:validation:Required
	FluencyId int64 `json:"fluencyId"`

	// CompetencyId Specify the numerical ID of the compenetency
	// +kubebuilder:validation:Required
	CompetencyId int64 `json:"competencyId"`

	// Comment Specify the comment
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Comment string `json:"comment"`
}

// PimEmployeeLanguageObservation are the observable fields of a PimEmployeeLanguage.
//
// These are the fields of the read response (PimEmployeeLanguageModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeLanguageObservation struct {
	// Language
	Language string `json:"language,omitempty"`

	// Fluency
	Fluency string `json:"fluency,omitempty"`

	// Competency
	Competency string `json:"competency,omitempty"`

	// Comment The comment regarding the language and fluency
	Comment string `json:"comment,omitempty"`
}

// A PimEmployeeLanguageSpec defines the desired state of a PimEmployeeLanguage.
type PimEmployeeLanguageSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeLanguageParameters `json:"forProvider"`
}

// A PimEmployeeLanguageStatus represents the observed state of a PimEmployeeLanguage.
type PimEmployeeLanguageStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeLanguageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeLanguage is a managed OrangeHRM pimEmployeeLanguage.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeLanguage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeLanguageSpec   `json:"spec"`
	Status PimEmployeeLanguageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeLanguageList contains a list of PimEmployeeLanguage
type PimEmployeeLanguageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeLanguage `json:"items"`
}

// PimEmployeeLanguage type metadata.
var (
	PimEmployeeLanguageKind             = reflect.TypeOf(PimEmployeeLanguage{}).Name()
	PimEmployeeLanguageGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeLanguageKind}.String()
	PimEmployeeLanguageKindAPIVersion   = PimEmployeeLanguageKind + "." + SchemeGroupVersion.String()
	PimEmployeeLanguageGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeLanguageKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeLanguage{}, &PimEmployeeLanguageList{})
}
