//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguage) DeepCopyInto(out *PimEmployeeLanguage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguage.
func (in *PimEmployeeLanguage) DeepCopy() *PimEmployeeLanguage {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeLanguage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguageList) DeepCopyInto(out *PimEmployeeLanguageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimEmployeeLanguage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguageList.
func (in *PimEmployeeLanguageList) DeepCopy() *PimEmployeeLanguageList {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeLanguageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguageObservation) DeepCopyInto(out *PimEmployeeLanguageObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguageObservation.
func (in *PimEmployeeLanguageObservation) DeepCopy() *PimEmployeeLanguageObservation {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguageParameters) DeepCopyInto(out *PimEmployeeLanguageParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguageParameters.
func (in *PimEmployeeLanguageParameters) DeepCopy() *PimEmployeeLanguageParameters {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguageSpec) DeepCopyInto(out *PimEmployeeLanguageSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguageSpec.
func (in *PimEmployeeLanguageSpec) DeepCopy() *PimEmployeeLanguageSpec {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeLanguageStatus) DeepCopyInto(out *PimEmployeeLanguageStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeLanguageStatus.
func (in *PimEmployeeLanguageStatus) DeepCopy() *PimEmployeeLanguageStatus {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeLanguageStatus)
	in.DeepCopyInto(out)
	return out
}
