// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &LeaveLeaveType{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// LeaveLeaveTypeParameters are the configurable fields of a LeaveLeaveType.
//
// These are the fields of the create request body (CreateALeaveTypeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// LeaveLeaveTypeObservation instead.
type LeaveLeaveTypeParameters struct {
	// Name
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Name string `json:"name"`

	// Situational
	// +optional
	Situational bool `json:"situational"`
}

// LeaveLeaveTypeObservation are the observable fields of a LeaveLeaveType.
//
// These are the fields of the read response (LeaveLeaveTypeModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type LeaveLeaveTypeObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Deleted
	Deleted bool `json:"deleted,omitempty"`

	// Situational
	Situational bool `json:"situational,omitempty"`
}

// A LeaveLeaveTypeSpec defines the desired state of a LeaveLeaveType.
type LeaveLeaveTypeSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              LeaveLeaveTypeParameters `json:"forProvider"`
}

// A LeaveLeaveTypeStatus represents the observed state of a LeaveLeaveType.
type LeaveLeaveTypeStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 LeaveLeaveTypeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A LeaveLeaveType is a managed OrangeHRM leaveLeaveType.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type LeaveLeaveType struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   LeaveLeaveTypeSpec   `json:"spec"`
	Status LeaveLeaveTypeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LeaveLeaveTypeList contains a list of LeaveLeaveType
type LeaveLeaveTypeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LeaveLeaveType `json:"items"`
}

// LeaveLeaveType type metadata.
var (
	LeaveLeaveTypeKind             = reflect.TypeOf(LeaveLeaveType{}).Name()
	LeaveLeaveTypeGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LeaveLeaveTypeKind}.String()
	LeaveLeaveTypeKindAPIVersion   = LeaveLeaveTypeKind + "." + SchemeGroupVersion.String()
	LeaveLeaveTypeGroupVersionKind = SchemeGroupVersion.WithKind(LeaveLeaveTypeKind)
)

func init() {
	SchemeBuilder.Register(&LeaveLeaveType{}, &LeaveLeaveTypeList{})
}
