// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// GenericObject is the GenericObject schema of the API description.
type GenericObject struct {
	Url  string   `json:"_url,omitempty"`
	Id   string   `json:"id,omitempty"`
	Type TypeEnum `json:"type,omitempty"`
}
