// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// RightsListAllOfItems is the RightsListAllOfItems schema of the API description.
type RightsListAllOfItems struct {
	Right string         `json:"Right,omitempty"`
	Group GroupReference `json:"Group,omitempty"`
	User  UserReference  `json:"User,omitempty"`
}
