// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ObjectMetadata is the ObjectMetadata schema of the API description.
type ObjectMetadata struct {
	Id            int32         `json:"id,omitempty"`
	Created       string        `json:"Created,omitempty"`
	Creator       UserReference `json:"Creator,omitempty"`
	LastUpdated   string        `json:"LastUpdated,omitempty"`
	LastUpdatedBy UserReference `json:"LastUpdatedBy,omitempty"`
}
