// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// HyperlinkMembers is the HyperlinkMembers schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type HyperlinkMembers struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
}
