// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// LifecyclesPostRequest is the LifecyclesPostRequest schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LifecyclesPostRequest struct {
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
}
