// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomFieldsUploadCustomFieldsValue is the CustomFieldsUploadCustomFieldsValue schema of the API description.
type CustomFieldsUploadCustomFieldsValue struct {
}
