// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CatalogPropertiesCommon is the CatalogPropertiesCommon schema of the API description.
type CatalogPropertiesCommon struct {
	Name        string      `json:"Name,omitempty"`
	Description string      `json:"Description,omitempty"`
	Lifecycle   string      `json:"Lifecycle,omitempty"`
	Disabled    PerlBoolean `json:"Disabled,omitempty"`
}
