// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// LifecycleReference is the LifecycleReference schema of the API description.
type LifecycleReference struct {
	Url  string `json:"_url,omitempty"`
	Id   RTID   `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
