// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// QueueIdNamePutRequest is the QueueIdNamePutRequest schema of the API description.
type QueueIdNamePutRequest struct {
	Name              string      `json:"Name,omitempty"`
	Description       string      `json:"Description,omitempty"`
	Lifecycle         string      `json:"Lifecycle,omitempty"`
	SubjectTag        string      `json:"SubjectTag,omitempty"`
	SortOrder         string      `json:"SortOrder,omitempty"`
	CorrespondAddress string      `json:"CorrespondAddress,omitempty"`
	CommentAddress    string      `json:"CommentAddress,omitempty"`
	SLADisabled       PerlBoolean `json:"SLADisabled,omitempty"`
	Disabled          PerlBoolean `json:"Disabled,omitempty"`
}
