// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// UserIdNameGet200ResponseAllOfHyperlinksInner is the UserIdNameGet200ResponseAllOfHyperlinksInner schema of the API description.
type UserIdNameGet200ResponseAllOfHyperlinksInner struct {
	Ref  string   `json:"ref,omitempty"`
	Url  string   `json:"_url,omitempty"`
	Id   RTID     `json:"id,omitempty"`
	Type TypeEnum `json:"type,omitempty"`
}
