// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// LifecycleDocument is the LifecycleDocument schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type LifecycleDocument struct {
	Type          string                               `json:"type,omitempty"`
	Initial       []string                             `json:"initial,omitempty"`
	Active        []string                             `json:"active,omitempty"`
	Inactive      []string                             `json:"inactive,omitempty"`
	Defaults      map[string]string                    `json:"defaults,omitempty"`
	Transitions   map[string][]string                  `json:"transitions,omitempty"`
	Rights        map[string]string                    `json:"rights,omitempty"`
	Actions       []LifecycleConfigurationActionsInner `json:"actions,omitempty"`
	Colors        map[string]string                    `json:"colors,omitempty"`
	Name          string                               `json:"name,omitempty"`
	CanonicalCase map[string]string                    `json:"canonical_case,omitempty"`
	Url           string                               `json:"_url,omitempty"`
}
