// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ArticleReference is the ArticleReference schema of the API description.
type ArticleReference struct {
	Url  string `json:"_url,omitempty"`
	Id   string `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
