// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// LifecycleConfiguration is the LifecycleConfiguration schema of the API description.
type LifecycleConfiguration struct {
	Type        string                   `json:"type,omitempty"`
	Initial     []string                 `json:"initial,omitempty"`
	Active      []string                 `json:"active,omitempty"`
	Inactive    []string                 `json:"inactive,omitempty"`
	Defaults    map[string]string        `json:"defaults,omitempty"`
	Transitions map[string][]string      `json:"transitions,omitempty"`
	Rights      map[string]string        `json:"rights,omitempty"`
	Actions     []map[string]interface{} `json:"actions,omitempty"`
	Colors      map[string]string        `json:"colors,omitempty"`
}
