// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// LifecyclesPostRequest is the LifecyclesPostRequest schema of the API description.
type LifecyclesPostRequest struct {
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
}
