// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomfieldIdValueIdGet200Response is the CustomfieldIdValueIdGet200Response schema of the API description.
type CustomfieldIdValueIdGet200Response struct {
	Id            int32         `json:"id,omitempty"`
	Created       string        `json:"Created,omitempty"`
	Creator       UserReference `json:"Creator,omitempty"`
	LastUpdated   string        `json:"LastUpdated,omitempty"`
	LastUpdatedBy UserReference `json:"LastUpdatedBy,omitempty"`
	Name          string        `json:"Name,omitempty"`
	Description   string        `json:"Description,omitempty"`
	SortOrder     string        `json:"SortOrder,omitempty"`
	Category      string        `json:"Category,omitempty"`
}
