// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// GroupIdPutRequest is the GroupIdPutRequest schema of the API description.
type GroupIdPutRequest struct {
	Name        string      `json:"Name,omitempty"`
	Description string      `json:"Description,omitempty"`
	Disabled    PerlBoolean `json:"Disabled,omitempty"`
}
