// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CatalogReference is the CatalogReference schema of the API description.
type CatalogReference struct {
	Url  string `json:"_url,omitempty"`
	Id   RTID   `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
