// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomFieldCommon is the CustomFieldCommon schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CustomFieldCommon struct {
	Name           string `json:"Name,omitempty"`
	Type           string `json:"Type,omitempty"`
	RenderType     string `json:"RenderType,omitempty"`
	LookupType     string `json:"LookupType,omitempty"`
	ValidationHint string `json:"ValidationHint,omitempty"`
}
