// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomFieldsArrayInner is the CustomFieldsArrayInner schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type CustomFieldsArrayInner struct {
	Id     RTID          `json:"id,omitempty"`
	Name   string        `json:"name,omitempty"`
	Values []interface{} `json:"values,omitempty"`
	Url    string        `json:"_url,omitempty"`
	Type   string        `json:"type,omitempty"`
}
