// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// QueueIdNameRightsPost201Response is the QueueIdNameRightsPost201Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type QueueIdNameRightsPost201Response struct {
	Right string             `json:"Right,omitempty"`
	Group PrincipalReference `json:"Group,omitempty"`
	User  PrincipalReference `json:"User,omitempty"`
}
