// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomFieldsUpload is the CustomFieldsUpload schema of the API description.
type CustomFieldsUpload struct {
	CustomFields map[string]CustomFieldsUploadCustomFieldsValue `json:"CustomFields,omitempty"`
}
