// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ClassIdNameGet200Response is the ClassIdNameGet200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ClassIdNameGet200Response struct {
	Id            RTID          `json:"id,omitempty"`
	Created       string        `json:"Created,omitempty"`
	Creator       UserReference `json:"Creator,omitempty"`
	LastUpdated   string        `json:"LastUpdated,omitempty"`
	LastUpdatedBy UserReference `json:"LastUpdatedBy,omitempty"`
	Name          string        `json:"Name,omitempty"`
	Description   string        `json:"Description,omitempty"`
	SortOrder     string        `json:"SortOrder,omitempty"`
	Disabled      PerlBoolean   `json:"Disabled,omitempty"`
}
