// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomfieldIdValuePostRequest is the CustomfieldIdValuePostRequest schema of the API description.
type CustomfieldIdValuePostRequest struct {
	Name        string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder   string `json:"SortOrder,omitempty"`
	Category    string `json:"Category,omitempty"`
}
