// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// HyperlinkMemberships is the HyperlinkMemberships schema of the API description.
type HyperlinkMemberships struct {
}
