// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// TicketLinksUpload is the TicketLinksUpload schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type TicketLinksUpload struct {
	DependsOn    TicketLink `json:"DependsOn,omitempty"`
	Child        TicketLink `json:"Child,omitempty"`
	ReferredToBy TicketLink `json:"ReferredToBy,omitempty"`
	Parent       TicketLink `json:"Parent,omitempty"`
	DependedOnBy TicketLink `json:"DependedOnBy,omitempty"`
	RefersTo     TicketLink `json:"RefersTo,omitempty"`
}
