// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// RightsBulk is the RightsBulk schema of the API description.
type RightsBulk struct {
	Grant  []RightGrant `json:"grant,omitempty"`
	Revoke []RightGrant `json:"revoke,omitempty"`
}
