// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// Hyperlink is the Hyperlink schema of the API description.
type Hyperlink struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
}
