// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ClassPropertiesCommon is the ClassPropertiesCommon schema of the API description.
type ClassPropertiesCommon struct {
	Name        string      `json:"Name,omitempty"`
	Description string      `json:"Description,omitempty"`
	SortOrder   string      `json:"SortOrder,omitempty"`
	Disabled    PerlBoolean `json:"Disabled,omitempty"`
}
