// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// TicketReference is the TicketReference schema of the API description.
type TicketReference struct {
	Url  string         `json:"_url,omitempty"`
	Id   string         `json:"id,omitempty"`
	Type ConstantTicket `json:"type,omitempty"`
}
