// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// HyperlinkCustomField is the HyperlinkCustomField schema of the API description.
type HyperlinkCustomField struct {
	Id   RTID                `json:"id,omitempty"`
	Name string              `json:"name,omitempty"`
	Type ConstantCustomField `json:"type,omitempty"`
}
