// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ConstantTicket is the ConstantTicket schema of the API description.
type ConstantTicket struct {
}
