// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// CustomroleIdGet200Response is the CustomroleIdGet200Response schema of the API description.
type CustomroleIdGet200Response struct {
	Id            int32         `json:"id,omitempty"`
	Created       string        `json:"Created,omitempty"`
	Creator       UserReference `json:"Creator,omitempty"`
	LastUpdated   string        `json:"LastUpdated,omitempty"`
	LastUpdatedBy UserReference `json:"LastUpdatedBy,omitempty"`
	Name          string        `json:"Name,omitempty"`
	Description   string        `json:"Description,omitempty"`
	MaxValues     string        `json:"MaxValues,omitempty"`
	EntryHint     string        `json:"EntryHint,omitempty"`
	LookupType    string        `json:"LookupType,omitempty"`
	Disabled      PerlBoolean   `json:"Disabled,omitempty"`
}
