// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// HyperlinkRights is the HyperlinkRights schema of the API description.
type HyperlinkRights struct {
}
