// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ArticleIdGet200Response is the ArticleIdGet200Response schema of the API description.
type ArticleIdGet200Response struct {
	Id            int32                    `json:"id,omitempty"`
	Created       string                   `json:"Created,omitempty"`
	Creator       UserReference            `json:"Creator,omitempty"`
	LastUpdated   string                   `json:"LastUpdated,omitempty"`
	LastUpdatedBy UserReference            `json:"LastUpdatedBy,omitempty"`
	CustomFields  []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Name          string                   `json:"Name,omitempty"`
	Summary       string                   `json:"Summary,omitempty"`
	SortOrder     string                   `json:"SortOrder,omitempty"`
	Class         ClassReference           `json:"Class,omitempty"`
	Parent        int32                    `json:"Parent,omitempty"`
	URI           string                   `json:"URI,omitempty"`
	Disabled      PerlBoolean              `json:"Disabled,omitempty"`
}
