// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// ArticleReference is the ArticleReference schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type ArticleReference struct {
	Url  string `json:"_url,omitempty"`
	Id   RTID   `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
