// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// RightsBulk is the RightsBulk schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type RightsBulk struct {
	Grant  []RightGrant `json:"grant,omitempty"`
	Revoke []RightGrant `json:"revoke,omitempty"`
}
