// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rt

// QueuesAllGet200Response is the QueuesAllGet200Response schema of the API description.
//
// allVars, not vars: a schema written as `allOf: [$ref, {...}]` keeps the
// inherited half in the parent, and a struct built from `vars` alone would
// silently drop `ref` and `_url` from every hyperlink.
type QueuesAllGet200Response struct {
	Page    int32            `json:"page,omitempty"`
	Pages   int32            `json:"pages,omitempty"`
	PerPage int32            `json:"per_page,omitempty"`
	Count   int32            `json:"count,omitempty"`
	Total   int32            `json:"total,omitempty"`
	Items   []QueueReference `json:"items,omitempty"`
}
