// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeScreenAttachment{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeScreenAttachmentParameters are the configurable fields of a PimEmployeeScreenAttachment.
//
// These are the fields of the create request body (UpdateAnEmployeesAttachmentOnAScreenRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeScreenAttachmentObservation instead.
type PimEmployeeScreenAttachmentParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// Screen The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="screen is immutable"
	Screen string `json:"screen"`

	// Description Specify the description of the attachment
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Description string `json:"description,omitempty"`

	// Attachment
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Attachment string `json:"attachment,omitempty"`
}

// PimEmployeeScreenAttachmentObservation are the observable fields of a PimEmployeeScreenAttachment.
//
// These are the fields of the read response (PimEmployeeAttachmentModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeScreenAttachmentObservation struct {
	// Id The numerical ID of the attachment
	Id int64 `json:"id,omitempty"`

	// Description The description of the attachment
	Description string `json:"description,omitempty"`

	// Filename The file name of the attachment
	Filename string `json:"filename,omitempty"`

	// Size The size of the attachment
	Size int64 `json:"size,omitempty"`

	// FileType The type of the attachment
	FileType string `json:"fileType,omitempty"`

	// AttachedBy The employee number of attachment uploader
	AttachedBy int64 `json:"attachedBy,omitempty"`

	// AttachedByName The name of the attachment uploader
	AttachedByName string `json:"attachedByName,omitempty"`

	// AttachedTime The time the attachment was uploaded
	AttachedTime string `json:"attachedTime,omitempty"`

	// AttachedDate The date the attachment was uplaoded
	AttachedDate string `json:"attachedDate,omitempty"`
}

// A PimEmployeeScreenAttachmentSpec defines the desired state of a PimEmployeeScreenAttachment.
type PimEmployeeScreenAttachmentSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeScreenAttachmentParameters `json:"forProvider"`
}

// A PimEmployeeScreenAttachmentStatus represents the observed state of a PimEmployeeScreenAttachment.
type PimEmployeeScreenAttachmentStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeScreenAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeScreenAttachment is a managed OrangeHRM pimEmployeeScreenAttachment.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeScreenAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeScreenAttachmentSpec   `json:"spec"`
	Status PimEmployeeScreenAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeScreenAttachmentList contains a list of PimEmployeeScreenAttachment
type PimEmployeeScreenAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeScreenAttachment `json:"items"`
}

// PimEmployeeScreenAttachment type metadata.
var (
	PimEmployeeScreenAttachmentKind             = reflect.TypeOf(PimEmployeeScreenAttachment{}).Name()
	PimEmployeeScreenAttachmentGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeScreenAttachmentKind}.String()
	PimEmployeeScreenAttachmentKindAPIVersion   = PimEmployeeScreenAttachmentKind + "." + SchemeGroupVersion.String()
	PimEmployeeScreenAttachmentGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeScreenAttachmentKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeScreenAttachment{}, &PimEmployeeScreenAttachmentList{})
}
