//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachment) DeepCopyInto(out *PimEmployeeScreenAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachment.
func (in *PimEmployeeScreenAttachment) DeepCopy() *PimEmployeeScreenAttachment {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeScreenAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachmentList) DeepCopyInto(out *PimEmployeeScreenAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimEmployeeScreenAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachmentList.
func (in *PimEmployeeScreenAttachmentList) DeepCopy() *PimEmployeeScreenAttachmentList {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeScreenAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachmentObservation) DeepCopyInto(out *PimEmployeeScreenAttachmentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachmentObservation.
func (in *PimEmployeeScreenAttachmentObservation) DeepCopy() *PimEmployeeScreenAttachmentObservation {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachmentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachmentParameters) DeepCopyInto(out *PimEmployeeScreenAttachmentParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachmentParameters.
func (in *PimEmployeeScreenAttachmentParameters) DeepCopy() *PimEmployeeScreenAttachmentParameters {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachmentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachmentSpec) DeepCopyInto(out *PimEmployeeScreenAttachmentSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachmentSpec.
func (in *PimEmployeeScreenAttachmentSpec) DeepCopy() *PimEmployeeScreenAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeScreenAttachmentStatus) DeepCopyInto(out *PimEmployeeScreenAttachmentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeScreenAttachmentStatus.
func (in *PimEmployeeScreenAttachmentStatus) DeepCopy() *PimEmployeeScreenAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeScreenAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}
