// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &LeaveLeaveEntitlement{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// LeaveLeaveEntitlementParameters are the configurable fields of a LeaveLeaveEntitlement.
//
// These are the fields of the create request body (AssignLeaveEntitlementsToEmployeesRequest), which is
// exactly what a person may write. Anything the server assigns is in
// LeaveLeaveEntitlementObservation instead.
type LeaveLeaveEntitlementParameters struct {
	// EmpNumber If not buk assign this is require
	// +optional
	EmpNumber int64 `json:"empNumber,omitempty"`

	// Entitlement
	// +kubebuilder:validation:Required
	Entitlement int64 `json:"entitlement"`

	// FromDate
	// +optional
	FromDate float64 `json:"fromDate,omitempty"`

	// ToDate
	// +kubebuilder:validation:Required
	ToDate float64 `json:"toDate"`

	// LeaveTypeId
	// +optional
	LeaveTypeId int64 `json:"leaveTypeId,omitempty"`

	// BulkAssign
	// +optional
	BulkAssign bool `json:"bulkAssign"`

	// LocationId
	// +optional
	LocationId int64 `json:"locationId,omitempty"`
}

// LeaveLeaveEntitlementObservation are the observable fields of a LeaveLeaveEntitlement.
//
// These are the fields of the read response (GetALeaveEntitlement200ResponseData) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type LeaveLeaveEntitlementObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Employee
	Employee string `json:"employee,omitempty"`

	// Entitlement
	Entitlement int64 `json:"entitlement,omitempty"`

	// DaysUsed
	DaysUsed int64 `json:"daysUsed,omitempty"`

	// LeaveType
	LeaveType string `json:"leaveType,omitempty"`

	// FromDate
	FromDate string `json:"fromDate,omitempty"`

	// ToDate
	ToDate string `json:"toDate,omitempty"`

	// CreditedDate
	CreditedDate float64 `json:"creditedDate,omitempty"`

	// EntitlementType
	EntitlementType string `json:"entitlementType,omitempty"`

	// Deleted
	Deleted bool `json:"deleted,omitempty"`

	// Deletable
	Deletable bool `json:"deletable,omitempty"`

	// UsageBreakdown
	UsageBreakdown string `json:"usageBreakdown,omitempty"`
}

// A LeaveLeaveEntitlementSpec defines the desired state of a LeaveLeaveEntitlement.
type LeaveLeaveEntitlementSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              LeaveLeaveEntitlementParameters `json:"forProvider"`
}

// A LeaveLeaveEntitlementStatus represents the observed state of a LeaveLeaveEntitlement.
type LeaveLeaveEntitlementStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 LeaveLeaveEntitlementObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A LeaveLeaveEntitlement is a managed OrangeHRM leaveLeaveEntitlement.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type LeaveLeaveEntitlement struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   LeaveLeaveEntitlementSpec   `json:"spec"`
	Status LeaveLeaveEntitlementStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LeaveLeaveEntitlementList contains a list of LeaveLeaveEntitlement
type LeaveLeaveEntitlementList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LeaveLeaveEntitlement `json:"items"`
}

// LeaveLeaveEntitlement type metadata.
var (
	LeaveLeaveEntitlementKind             = reflect.TypeOf(LeaveLeaveEntitlement{}).Name()
	LeaveLeaveEntitlementGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LeaveLeaveEntitlementKind}.String()
	LeaveLeaveEntitlementKindAPIVersion   = LeaveLeaveEntitlementKind + "." + SchemeGroupVersion.String()
	LeaveLeaveEntitlementGroupVersionKind = SchemeGroupVersion.WithKind(LeaveLeaveEntitlementKind)
)

func init() {
	SchemeBuilder.Register(&LeaveLeaveEntitlement{}, &LeaveLeaveEntitlementList{})
}
