// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AdminPayGradeCurrency{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AdminPayGradeCurrencyParameters are the configurable fields of a AdminPayGradeCurrency.
//
// These are the fields of the create request body (CreateAPayGradeCurrencyRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AdminPayGradeCurrencyObservation instead.
type AdminPayGradeCurrencyParameters struct {
	// PayGradeId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="payGradeId is immutable"
	PayGradeId string `json:"payGradeId"`

	// CurrencyId
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	CurrencyId string `json:"currencyId"`

	// MaxSalary
	// +kubebuilder:validation:Required
	MaxSalary int64 `json:"maxSalary"`

	// MinSalary
	// +kubebuilder:validation:Required
	MinSalary int64 `json:"minSalary"`
}

// AdminPayGradeCurrencyObservation are the observable fields of a AdminPayGradeCurrency.
//
// These are the fields of the read response (AdminPayGradeCurrencyModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AdminPayGradeCurrencyObservation struct {
	// MinSalary
	MinSalary float64 `json:"minSalary,omitempty"`

	// MaxSalary
	MaxSalary float64 `json:"maxSalary,omitempty"`

	// CurrencyType
	CurrencyType string `json:"currencyType,omitempty"`
}

// A AdminPayGradeCurrencySpec defines the desired state of a AdminPayGradeCurrency.
type AdminPayGradeCurrencySpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AdminPayGradeCurrencyParameters `json:"forProvider"`
}

// A AdminPayGradeCurrencyStatus represents the observed state of a AdminPayGradeCurrency.
type AdminPayGradeCurrencyStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AdminPayGradeCurrencyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AdminPayGradeCurrency is a managed OrangeHRM adminPayGradeCurrency.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AdminPayGradeCurrency struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AdminPayGradeCurrencySpec   `json:"spec"`
	Status AdminPayGradeCurrencyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdminPayGradeCurrencyList contains a list of AdminPayGradeCurrency
type AdminPayGradeCurrencyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdminPayGradeCurrency `json:"items"`
}

// AdminPayGradeCurrency type metadata.
var (
	AdminPayGradeCurrencyKind             = reflect.TypeOf(AdminPayGradeCurrency{}).Name()
	AdminPayGradeCurrencyGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdminPayGradeCurrencyKind}.String()
	AdminPayGradeCurrencyKindAPIVersion   = AdminPayGradeCurrencyKind + "." + SchemeGroupVersion.String()
	AdminPayGradeCurrencyGroupVersionKind = SchemeGroupVersion.WithKind(AdminPayGradeCurrencyKind)
)

func init() {
	SchemeBuilder.Register(&AdminPayGradeCurrency{}, &AdminPayGradeCurrencyList{})
}
