//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrency) DeepCopyInto(out *AdminPayGradeCurrency) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrency.
func (in *AdminPayGradeCurrency) DeepCopy() *AdminPayGradeCurrency {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrency)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminPayGradeCurrency) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrencyList) DeepCopyInto(out *AdminPayGradeCurrencyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdminPayGradeCurrency, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrencyList.
func (in *AdminPayGradeCurrencyList) DeepCopy() *AdminPayGradeCurrencyList {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrencyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminPayGradeCurrencyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrencyObservation) DeepCopyInto(out *AdminPayGradeCurrencyObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrencyObservation.
func (in *AdminPayGradeCurrencyObservation) DeepCopy() *AdminPayGradeCurrencyObservation {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrencyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrencyParameters) DeepCopyInto(out *AdminPayGradeCurrencyParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrencyParameters.
func (in *AdminPayGradeCurrencyParameters) DeepCopy() *AdminPayGradeCurrencyParameters {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrencyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrencySpec) DeepCopyInto(out *AdminPayGradeCurrencySpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrencySpec.
func (in *AdminPayGradeCurrencySpec) DeepCopy() *AdminPayGradeCurrencySpec {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrencySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminPayGradeCurrencyStatus) DeepCopyInto(out *AdminPayGradeCurrencyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminPayGradeCurrencyStatus.
func (in *AdminPayGradeCurrencyStatus) DeepCopy() *AdminPayGradeCurrencyStatus {
	if in == nil {
		return nil
	}
	out := new(AdminPayGradeCurrencyStatus)
	in.DeepCopyInto(out)
	return out
}
