//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatus) DeepCopyInto(out *AdminEmploymentStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatus.
func (in *AdminEmploymentStatus) DeepCopy() *AdminEmploymentStatus {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminEmploymentStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatusList) DeepCopyInto(out *AdminEmploymentStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdminEmploymentStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatusList.
func (in *AdminEmploymentStatusList) DeepCopy() *AdminEmploymentStatusList {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdminEmploymentStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatusObservation) DeepCopyInto(out *AdminEmploymentStatusObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatusObservation.
func (in *AdminEmploymentStatusObservation) DeepCopy() *AdminEmploymentStatusObservation {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatusObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatusParameters) DeepCopyInto(out *AdminEmploymentStatusParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatusParameters.
func (in *AdminEmploymentStatusParameters) DeepCopy() *AdminEmploymentStatusParameters {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatusParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatusSpec) DeepCopyInto(out *AdminEmploymentStatusSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatusSpec.
func (in *AdminEmploymentStatusSpec) DeepCopy() *AdminEmploymentStatusSpec {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminEmploymentStatusStatus) DeepCopyInto(out *AdminEmploymentStatusStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminEmploymentStatusStatus.
func (in *AdminEmploymentStatusStatus) DeepCopy() *AdminEmploymentStatusStatus {
	if in == nil {
		return nil
	}
	out := new(AdminEmploymentStatusStatus)
	in.DeepCopyInto(out)
	return out
}
