// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &Customrole{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// CustomroleParameters are the configurable fields of a Customrole.
//
// These are the fields of the create request body (), which is
// exactly what a person may write. Anything the server assigns is in
// CustomroleObservation instead.
type CustomroleParameters struct {
}

// CustomroleObservation are the observable fields of a Customrole.
//
// These are the fields of the read response (CustomroleIdGet200Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type CustomroleObservation struct {
	// Id Integer identifier
	Id string `json:"id,omitempty"`

	// Created
	Created string `json:"Created,omitempty"`

	// Creator
	Creator string `json:"Creator,omitempty"`

	// LastUpdated
	LastUpdated string `json:"LastUpdated,omitempty"`

	// LastUpdatedBy
	LastUpdatedBy string `json:"LastUpdatedBy,omitempty"`

	// Name
	Name string `json:"Name,omitempty"`

	// Description
	Description string `json:"Description,omitempty"`

	// MaxValues Whether the role takes a single principal.
	MaxValues string `json:"MaxValues,omitempty"`

	// EntryHint
	EntryHint string `json:"EntryHint,omitempty"`

	// LookupType What type of object this role applies to.
	LookupType string `json:"LookupType,omitempty"`

	// Disabled
	Disabled string `json:"Disabled,omitempty"`
}

// A CustomroleSpec defines the desired state of a Customrole.
type CustomroleSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              CustomroleParameters `json:"forProvider"`
}

// A CustomroleStatus represents the observed state of a Customrole.
type CustomroleStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 CustomroleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A Customrole is a managed RT customrole.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type Customrole struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomroleSpec   `json:"spec"`
	Status CustomroleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomroleList contains a list of Customrole
type CustomroleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Customrole `json:"items"`
}

// Customrole type metadata.
var (
	CustomroleKind             = reflect.TypeOf(Customrole{}).Name()
	CustomroleGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomroleKind}.String()
	CustomroleKindAPIVersion   = CustomroleKind + "." + SchemeGroupVersion.String()
	CustomroleGroupVersionKind = SchemeGroupVersion.WithKind(CustomroleKind)
)

func init() {
	SchemeBuilder.Register(&Customrole{}, &CustomroleList{})
}
