// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &RecruitmentCandidate{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// RecruitmentCandidateParameters are the configurable fields of a RecruitmentCandidate.
//
// These are the fields of the create request body (CreateACandidateRequest), which is
// exactly what a person may write. Anything the server assigns is in
// RecruitmentCandidateObservation instead.
type RecruitmentCandidateParameters struct {
	// FirstName
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	FirstName string `json:"firstName"`

	// MiddleName
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	MiddleName string `json:"middleName,omitempty"`

	// LastName
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	LastName string `json:"lastName"`

	// Email
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Email string `json:"email"`

	// ContactNumber
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	ContactNumber string `json:"contactNumber,omitempty"`

	// VacancyId
	// +optional
	VacancyId int64 `json:"vacancyId,omitempty"`

	// Keywords
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Keywords string `json:"keywords,omitempty"`

	// Comment
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Comment string `json:"comment,omitempty"`

	// DateOfApplication
	// +optional
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	DateOfApplication string `json:"dateOfApplication,omitempty"`

	// ConsentToKeepData
	// +optional
	ConsentToKeepData bool `json:"consentToKeepData"`
}

// RecruitmentCandidateObservation are the observable fields of a RecruitmentCandidate.
//
// These are the fields of the read response (RecruitmentCandidateModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type RecruitmentCandidateObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// FirstName
	FirstName string `json:"firstName,omitempty"`

	// MiddleName
	MiddleName string `json:"middleName,omitempty"`

	// LastName
	LastName string `json:"lastName,omitempty"`

	// Email
	Email string `json:"email,omitempty"`
}

// A RecruitmentCandidateSpec defines the desired state of a RecruitmentCandidate.
type RecruitmentCandidateSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              RecruitmentCandidateParameters `json:"forProvider"`
}

// A RecruitmentCandidateStatus represents the observed state of a RecruitmentCandidate.
type RecruitmentCandidateStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 RecruitmentCandidateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A RecruitmentCandidate is a managed OrangeHRM recruitmentCandidate.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type RecruitmentCandidate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   RecruitmentCandidateSpec   `json:"spec"`
	Status RecruitmentCandidateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RecruitmentCandidateList contains a list of RecruitmentCandidate
type RecruitmentCandidateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RecruitmentCandidate `json:"items"`
}

// RecruitmentCandidate type metadata.
var (
	RecruitmentCandidateKind             = reflect.TypeOf(RecruitmentCandidate{}).Name()
	RecruitmentCandidateGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RecruitmentCandidateKind}.String()
	RecruitmentCandidateKindAPIVersion   = RecruitmentCandidateKind + "." + SchemeGroupVersion.String()
	RecruitmentCandidateGroupVersionKind = SchemeGroupVersion.WithKind(RecruitmentCandidateKind)
)

func init() {
	SchemeBuilder.Register(&RecruitmentCandidate{}, &RecruitmentCandidateList{})
}
