//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigration) DeepCopyInto(out *PimEmployeeImmigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigration.
func (in *PimEmployeeImmigration) DeepCopy() *PimEmployeeImmigration {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeImmigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigrationList) DeepCopyInto(out *PimEmployeeImmigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimEmployeeImmigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigrationList.
func (in *PimEmployeeImmigrationList) DeepCopy() *PimEmployeeImmigrationList {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeImmigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigrationObservation) DeepCopyInto(out *PimEmployeeImmigrationObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigrationObservation.
func (in *PimEmployeeImmigrationObservation) DeepCopy() *PimEmployeeImmigrationObservation {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigrationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigrationParameters) DeepCopyInto(out *PimEmployeeImmigrationParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigrationParameters.
func (in *PimEmployeeImmigrationParameters) DeepCopy() *PimEmployeeImmigrationParameters {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigrationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigrationSpec) DeepCopyInto(out *PimEmployeeImmigrationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigrationSpec.
func (in *PimEmployeeImmigrationSpec) DeepCopy() *PimEmployeeImmigrationSpec {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeImmigrationStatus) DeepCopyInto(out *PimEmployeeImmigrationStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeImmigrationStatus.
func (in *PimEmployeeImmigrationStatus) DeepCopy() *PimEmployeeImmigrationStatus {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeImmigrationStatus)
	in.DeepCopyInto(out)
	return out
}
