//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomField) DeepCopyInto(out *PimCustomField) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomField.
func (in *PimCustomField) DeepCopy() *PimCustomField {
	if in == nil {
		return nil
	}
	out := new(PimCustomField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimCustomField) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomFieldList) DeepCopyInto(out *PimCustomFieldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimCustomField, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomFieldList.
func (in *PimCustomFieldList) DeepCopy() *PimCustomFieldList {
	if in == nil {
		return nil
	}
	out := new(PimCustomFieldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimCustomFieldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomFieldObservation) DeepCopyInto(out *PimCustomFieldObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomFieldObservation.
func (in *PimCustomFieldObservation) DeepCopy() *PimCustomFieldObservation {
	if in == nil {
		return nil
	}
	out := new(PimCustomFieldObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomFieldParameters) DeepCopyInto(out *PimCustomFieldParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomFieldParameters.
func (in *PimCustomFieldParameters) DeepCopy() *PimCustomFieldParameters {
	if in == nil {
		return nil
	}
	out := new(PimCustomFieldParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomFieldSpec) DeepCopyInto(out *PimCustomFieldSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomFieldSpec.
func (in *PimCustomFieldSpec) DeepCopy() *PimCustomFieldSpec {
	if in == nil {
		return nil
	}
	out := new(PimCustomFieldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimCustomFieldStatus) DeepCopyInto(out *PimCustomFieldStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimCustomFieldStatus.
func (in *PimCustomFieldStatus) DeepCopy() *PimCustomFieldStatus {
	if in == nil {
		return nil
	}
	out := new(PimCustomFieldStatus)
	in.DeepCopyInto(out)
	return out
}
