//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareComment) DeepCopyInto(out *BuzzShareComment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareComment.
func (in *BuzzShareComment) DeepCopy() *BuzzShareComment {
	if in == nil {
		return nil
	}
	out := new(BuzzShareComment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuzzShareComment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareCommentList) DeepCopyInto(out *BuzzShareCommentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuzzShareComment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareCommentList.
func (in *BuzzShareCommentList) DeepCopy() *BuzzShareCommentList {
	if in == nil {
		return nil
	}
	out := new(BuzzShareCommentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuzzShareCommentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareCommentObservation) DeepCopyInto(out *BuzzShareCommentObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareCommentObservation.
func (in *BuzzShareCommentObservation) DeepCopy() *BuzzShareCommentObservation {
	if in == nil {
		return nil
	}
	out := new(BuzzShareCommentObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareCommentParameters) DeepCopyInto(out *BuzzShareCommentParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareCommentParameters.
func (in *BuzzShareCommentParameters) DeepCopy() *BuzzShareCommentParameters {
	if in == nil {
		return nil
	}
	out := new(BuzzShareCommentParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareCommentSpec) DeepCopyInto(out *BuzzShareCommentSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareCommentSpec.
func (in *BuzzShareCommentSpec) DeepCopy() *BuzzShareCommentSpec {
	if in == nil {
		return nil
	}
	out := new(BuzzShareCommentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareCommentStatus) DeepCopyInto(out *BuzzShareCommentStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareCommentStatus.
func (in *BuzzShareCommentStatus) DeepCopy() *BuzzShareCommentStatus {
	if in == nil {
		return nil
	}
	out := new(BuzzShareCommentStatus)
	in.DeepCopyInto(out)
	return out
}
