// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeDependent{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeDependentParameters are the configurable fields of a PimEmployeeDependent.
//
// These are the fields of the create request body (AddADependentToAnEmployeeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeDependentObservation instead.
type PimEmployeeDependentParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// Name Specify the name of the dependent
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// RelationshipType Specify the relationship type
	// +kubebuilder:validation:Required
	RelationshipType string `json:"relationshipType"`

	// Relationship Specify additional details of the relationship
	// +optional
	Relationship string `json:"relationship,omitempty"`

	// DateOfBirth Specify the date of birth of the dependent
	// +optional
	DateOfBirth string `json:"dateOfBirth,omitempty"`
}

// PimEmployeeDependentObservation are the observable fields of a PimEmployeeDependent.
//
// These are the fields of the read response (PimEmployeeDependentModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeDependentObservation struct {
	// Id The numerical ID of the dependent
	Id int64 `json:"id,omitempty"`

	// Name The name of the dependent
	Name string `json:"name,omitempty"`

	// RelationshipType The relationship type between the employee and the dependent (child or other)
	RelationshipType string `json:"relationshipType,omitempty"`

	// Relationship Additional details of the relationship
	Relationship string `json:"relationship,omitempty"`

	// DateOfBirth The date of birth of the dependent
	DateOfBirth string `json:"dateOfBirth,omitempty"`
}

// A PimEmployeeDependentSpec defines the desired state of a PimEmployeeDependent.
type PimEmployeeDependentSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeDependentParameters `json:"forProvider"`
}

// A PimEmployeeDependentStatus represents the observed state of a PimEmployeeDependent.
type PimEmployeeDependentStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeDependentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeDependent is a managed OrangeHRM pimEmployeeDependent.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeDependent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeDependentSpec   `json:"spec"`
	Status PimEmployeeDependentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeDependentList contains a list of PimEmployeeDependent
type PimEmployeeDependentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeDependent `json:"items"`
}

// PimEmployeeDependent type metadata.
var (
	PimEmployeeDependentKind             = reflect.TypeOf(PimEmployeeDependent{}).Name()
	PimEmployeeDependentGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeDependentKind}.String()
	PimEmployeeDependentKindAPIVersion   = PimEmployeeDependentKind + "." + SchemeGroupVersion.String()
	PimEmployeeDependentGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeDependentKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeDependent{}, &PimEmployeeDependentList{})
}
