// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AuthOpenidProvider{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AuthOpenidProviderParameters are the configurable fields of a AuthOpenidProvider.
//
// These are the fields of the create request body (CreateOpenidProviderRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AuthOpenidProviderObservation instead.
type AuthOpenidProviderParameters struct {
	// Name
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Name string `json:"name"`

	// Url
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Url string `json:"url"`

	// Status
	// +optional
	Status bool `json:"status"`

	// ClientId
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	ClientId string `json:"clientId"`

	// ClientSecret
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	ClientSecret string `json:"clientSecret"`
}

// AuthOpenidProviderObservation are the observable fields of a AuthOpenidProvider.
//
// These are the fields of the read response (OpenIdConnectProviderModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AuthOpenidProviderObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// ProviderName
	ProviderName string `json:"providerName,omitempty"`

	// ProviderUrl
	ProviderUrl string `json:"providerUrl,omitempty"`

	// Status
	Status bool `json:"status,omitempty"`

	// ClientId
	ClientId string `json:"clientId,omitempty"`
}

// A AuthOpenidProviderSpec defines the desired state of a AuthOpenidProvider.
type AuthOpenidProviderSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AuthOpenidProviderParameters `json:"forProvider"`
}

// A AuthOpenidProviderStatus represents the observed state of a AuthOpenidProvider.
type AuthOpenidProviderStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AuthOpenidProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AuthOpenidProvider is a managed OrangeHRM authOpenidProvider.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AuthOpenidProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AuthOpenidProviderSpec   `json:"spec"`
	Status AuthOpenidProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthOpenidProviderList contains a list of AuthOpenidProvider
type AuthOpenidProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthOpenidProvider `json:"items"`
}

// AuthOpenidProvider type metadata.
var (
	AuthOpenidProviderKind             = reflect.TypeOf(AuthOpenidProvider{}).Name()
	AuthOpenidProviderGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AuthOpenidProviderKind}.String()
	AuthOpenidProviderKindAPIVersion   = AuthOpenidProviderKind + "." + SchemeGroupVersion.String()
	AuthOpenidProviderGroupVersionKind = SchemeGroupVersion.WithKind(AuthOpenidProviderKind)
)

func init() {
	SchemeBuilder.Register(&AuthOpenidProvider{}, &AuthOpenidProviderList{})
}
