//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLog) DeepCopyInto(out *PerformanceTrackerLog) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLog.
func (in *PerformanceTrackerLog) DeepCopy() *PerformanceTrackerLog {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceTrackerLog) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLogList) DeepCopyInto(out *PerformanceTrackerLogList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerformanceTrackerLog, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLogList.
func (in *PerformanceTrackerLogList) DeepCopy() *PerformanceTrackerLogList {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLogList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceTrackerLogList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLogObservation) DeepCopyInto(out *PerformanceTrackerLogObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLogObservation.
func (in *PerformanceTrackerLogObservation) DeepCopy() *PerformanceTrackerLogObservation {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLogObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLogParameters) DeepCopyInto(out *PerformanceTrackerLogParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLogParameters.
func (in *PerformanceTrackerLogParameters) DeepCopy() *PerformanceTrackerLogParameters {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLogParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLogSpec) DeepCopyInto(out *PerformanceTrackerLogSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLogSpec.
func (in *PerformanceTrackerLogSpec) DeepCopy() *PerformanceTrackerLogSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLogSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceTrackerLogStatus) DeepCopyInto(out *PerformanceTrackerLogStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceTrackerLogStatus.
func (in *PerformanceTrackerLogStatus) DeepCopy() *PerformanceTrackerLogStatus {
	if in == nil {
		return nil
	}
	out := new(PerformanceTrackerLogStatus)
	in.DeepCopyInto(out)
	return out
}
