// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package buzz_share

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/crossplane/crossplane-runtime/v2/pkg/controller"
	"github.com/crossplane/crossplane-runtime/v2/pkg/errors"
	"github.com/crossplane/crossplane-runtime/v2/pkg/event"
	"github.com/crossplane/crossplane-runtime/v2/pkg/feature"
	"github.com/crossplane/crossplane-runtime/v2/pkg/meta"
	"github.com/crossplane/crossplane-runtime/v2/pkg/ratelimiter"
	"github.com/crossplane/crossplane-runtime/v2/pkg/reconciler/managed"
	"github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	"github.com/crossplane/crossplane-runtime/v2/pkg/statemetrics"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

	"github.com/n-at-han-k/crossplane-provider-orangehrm/apis/buzz_share/v1alpha1"
	apisv1alpha1 "github.com/n-at-han-k/crossplane-provider-orangehrm/apis/v1alpha1"
	"github.com/n-at-han-k/crossplane-provider-orangehrm/internal/clients/orangehrm"
)

const (
	errTrackPCUsage = "cannot track ProviderConfig usage"
	errGetPC        = "cannot get ProviderConfig"
	errGetCPC       = "cannot get ClusterProviderConfig"
	errGetCreds     = "cannot get credentials"
	errNewClient    = "cannot create new Service"

	errGet    = "cannot get OrangeHRM buzzShare"
	errCreate = "cannot create OrangeHRM buzzShare"
	errUpdate = "cannot update OrangeHRM buzzShare"
	errDelete = "cannot delete OrangeHRM buzzShare"
	errParams = "cannot build the OrangeHRM buzzShare request body"
	errParse  = "cannot parse the OrangeHRM buzzShare response"

	// errNoID guards the one failure mode that silently leaks a resource: the
	// create succeeds but nothing in the answer carries an identifier. Setting
	// an empty external name would make every later Observe report
	// ResourceExists: false and create another one, forever.
	errNoID = "OrangeHRM returned no buzzShare identifier from create; refusing to record an empty external name (one may have been created and needs manual cleanup)"
)

// newService builds the API client from the extracted credentials.
var newService = func(creds []byte) (*orangehrm.Client, error) {
	return orangehrm.NewClientFromCredentials(creds)
}

// SetupGated adds a controller that reconciles BuzzShare managed resources with safe-start support.
func SetupGated(mgr ctrl.Manager, o controller.Options) error {
	o.Gate.Register(func() {
		if err := Setup(mgr, o); err != nil {
			panic(errors.Wrap(err, "cannot setup BuzzShare controller"))
		}
	}, v1alpha1.BuzzShareGroupVersionKind)
	return nil
}

// Setup adds a controller that reconciles BuzzShare managed resources.
func Setup(mgr ctrl.Manager, o controller.Options) error {
	name := managed.ControllerName(v1alpha1.BuzzShareGroupKind)

	opts := []managed.ReconcilerOption{
		managed.WithTypedExternalConnector[*v1alpha1.BuzzShare](&connector{
			kube:         mgr.GetClient(),
			usage:        resource.NewProviderConfigUsageTracker(mgr.GetClient(), &apisv1alpha1.ProviderConfigUsage{}),
			newServiceFn: newService,
		}),
		managed.WithLogger(o.Logger.WithValues("controller", name)),
		managed.WithPollInterval(o.PollInterval),
		managed.WithRecorder(event.NewAPIRecorder(mgr.GetEventRecorderFor(name))), //nolint:staticcheck // Crossplane has not moved to the new events API yet.
	}

	if o.Features.Enabled(feature.EnableBetaManagementPolicies) {
		opts = append(opts, managed.WithManagementPolicies())
	}

	if o.Features.Enabled(feature.EnableAlphaChangeLogs) {
		opts = append(opts, managed.WithChangeLogger(o.ChangeLogOptions.ChangeLogger))
	}

	if o.MetricOptions != nil {
		opts = append(opts, managed.WithMetricRecorder(o.MetricOptions.MRMetrics))
	}

	if o.MetricOptions != nil && o.MetricOptions.MRStateMetrics != nil {
		stateMetricsRecorder := statemetrics.NewMRStateRecorder(
			mgr.GetClient(), o.Logger, o.MetricOptions.MRStateMetrics, &v1alpha1.BuzzShareList{}, o.MetricOptions.PollStateMetricInterval,
		)
		if err := mgr.Add(stateMetricsRecorder); err != nil {
			return errors.Wrap(err, "cannot register MR state metrics recorder for kind v1alpha1.BuzzShareList")
		}
	}

	r := managed.NewReconciler(mgr, resource.ManagedKind(v1alpha1.BuzzShareGroupVersionKind), opts...)

	return ctrl.NewControllerManagedBy(mgr).
		Named(name).
		WithOptions(o.ForControllerRuntime()).
		WithEventFilter(resource.DesiredStateChanged()).
		For(&v1alpha1.BuzzShare{}).
		Complete(ratelimiter.NewReconciler(name, r, o.GlobalRateLimiter))
}

type connector struct {
	kube         client.Client
	usage        *resource.ProviderConfigUsageTracker
	newServiceFn func(creds []byte) (*orangehrm.Client, error)
}

// Connect tracks the ProviderConfig usage, reads the (Cluster)ProviderConfig
// the resource names, extracts its credentials and forms a client from them.
func (c *connector) Connect(ctx context.Context, cr *v1alpha1.BuzzShare) (managed.TypedExternalClient[*v1alpha1.BuzzShare], error) {
	if err := c.usage.Track(ctx, cr); err != nil {
		return nil, errors.Wrap(err, errTrackPCUsage)
	}

	var cd apisv1alpha1.ProviderCredentials

	ref := cr.GetProviderConfigReference()

	switch ref.Kind {
	case "ProviderConfig":
		pc := &apisv1alpha1.ProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name, Namespace: cr.GetNamespace()}, pc); err != nil {
			return nil, errors.Wrap(err, errGetPC)
		}
		cd = pc.Spec.Credentials
	case "ClusterProviderConfig":
		cpc := &apisv1alpha1.ClusterProviderConfig{}
		if err := c.kube.Get(ctx, types.NamespacedName{Name: ref.Name}, cpc); err != nil {
			return nil, errors.Wrap(err, errGetCPC)
		}
		cd = cpc.Spec.Credentials
	default:
		return nil, errors.Errorf("unsupported provider config kind: %s", ref.Kind)
	}

	data, err := resource.CommonCredentialExtractor(ctx, cd.Source, c.kube, cd.CommonCredentialSelectors)
	if err != nil {
		return nil, errors.Wrap(err, errGetCreds)
	}

	svc, err := c.newServiceFn(data)
	if err != nil {
		return nil, errors.Wrap(err, errNewClient)
	}

	return &external{service: svc}, nil
}

type external struct {
	service *orangehrm.Client
}

// desired projects spec.forProvider onto the create request body. The JSON
// fields are strings in the CRD and real values on the wire, so they are
// unmarshalled here rather than passed through.
func desired(cr *v1alpha1.BuzzShare) (*orangehrm.ShareAPostRequest, error) {
	body := &orangehrm.ShareAPostRequest{}

	body.Text = cr.Spec.ForProvider.Text
	body.ShareId = int32(cr.Spec.ForProvider.ShareId)

	return body, nil
}

// observation projects the read response onto status.atProvider.
func observation(in *orangehrm.BuzzShareModel) (v1alpha1.BuzzShareObservation, error) {
	out := v1alpha1.BuzzShareObservation{}

	if raw, err := json.Marshal(in.Share); err == nil {
		out.Share = string(raw)
	} else {
		return out, errors.Wrap(err, "share")
	}
	if raw, err := json.Marshal(in.Post); err == nil {
		out.Post = string(raw)
	} else {
		return out, errors.Wrap(err, "post")
	}
	if raw, err := json.Marshal(in.Employee); err == nil {
		out.Employee = string(raw)
	} else {
		return out, errors.Wrap(err, "employee")
	}

	return out, nil
}

// upToDate compares only the fields the server answers under the same name
// and the same shape. A field it does not echo back -- a password, a body the
// server reshapes on the way out -- cannot be diffed without reporting drift
// on every reconcile, so it is left alone.
func upToDate(cr *v1alpha1.BuzzShare, observed *orangehrm.BuzzShareModel) bool {

	return true
}

// jsonEqual compares two JSON documents by value rather than by text, so that
// a server re-ordering an object's keys is not a permanent diff.
func jsonEqual(a, b string) bool {
	var left, right any

	if err := json.Unmarshal([]byte(a), &left); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(b), &right); err != nil {
		return false
	}

	x, err := json.Marshal(left)
	if err != nil {
		return false
	}
	y, err := json.Marshal(right)
	if err != nil {
		return false
	}

	return string(x) == string(y)
}

func (c *external) Observe(ctx context.Context, cr *v1alpha1.BuzzShare) (managed.ExternalObservation, error) {
	// This API offers no read for a buzzShare, so nothing can be observed
	// and nothing can be reported as drifted.
	//
	// Whether it EXISTS cannot come from the external name either:
	// crossplane-runtime's default initializer is NewNameAsExternalName, so
	// the annotation is already set to the resource's own name before the
	// first Observe ever runs. Reading existence off it would report
	// ResourceExists on the first pass, Create would never be called, and the
	// resource would sit there Available having done nothing at all.
	//
	// What this controller does know is whether IT has created the
	// buzzShare -- which is what the Ready condition it set at the end of
	// Create says, and that condition is persisted with the status.
	if cr.Status.GetCondition(xpv2.TypeReady).Reason != xpv2.ReasonAvailable {
		return managed.ExternalObservation{ResourceExists: false}, nil
	}

	return managed.ExternalObservation{
		ResourceExists:   true,
		ResourceUpToDate: true,
	}, nil
}

func (c *external) Create(ctx context.Context, cr *v1alpha1.BuzzShare) (managed.ExternalCreation, error) {
	cr.Status.SetConditions(xpv2.Creating())

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errParams)
	}

	respBody, location, err := c.service.DoCreateRequest(ctx, "POST", "/api/v2/buzz/shares", body)
	if err != nil {
		return managed.ExternalCreation{}, errors.Wrap(err, errCreate)
	}

	id := ""

	if len(respBody) == 0 {
		id = orangehrm.IDFromLocation(location)
	} else {
		var envelope orangehrm.ShareAPost200Response
		if err := json.Unmarshal(respBody, &envelope); err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		created := envelope.Data
		// The document describes no identifier on what this create answers, so
		// the Location header is all there is.
		id = orangehrm.IDFromLocation(location)

		at, err := observation(&created)
		if err != nil {
			return managed.ExternalCreation{}, errors.Wrap(err, errParse)
		}
		cr.Status.AtProvider = at
	}

	if id == "" {
		return managed.ExternalCreation{}, errors.New(errNoID)
	}

	meta.SetExternalName(cr, id)

	// The only record that this buzzShare was created: with no read,
	// Observe has nothing else to tell "created" from "not yet".
	cr.Status.SetConditions(xpv2.Available())

	return managed.ExternalCreation{}, nil
}

func (c *external) Update(ctx context.Context, cr *v1alpha1.BuzzShare) (managed.ExternalUpdate, error) {
	id := meta.GetExternalName(cr)
	if id == "" {
		return managed.ExternalUpdate{}, errors.New(errUpdate)
	}

	body, err := desired(cr)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errParams)
	}

	respBody, err := c.service.DoRequest(ctx, "PUT", fmt.Sprintf("/api/v2/buzz/shares/%v", id), body)
	if err != nil {
		return managed.ExternalUpdate{}, errors.Wrap(err, errUpdate)
	}

	// The update's answer is not read: the next Observe reports the new state,
	// which is where status.atProvider comes from anyway, and a PUT that
	// answers something other than the record -- a bulk endpoint answering a
	// count -- would fail to parse on every successful update.
	_ = respBody

	return managed.ExternalUpdate{}, nil
}

func (c *external) Delete(ctx context.Context, cr *v1alpha1.BuzzShare) (managed.ExternalDelete, error) {
	cr.Status.SetConditions(xpv2.Deleting())

	id := meta.GetExternalName(cr)
	if id == "" {
		// Never created; nothing to destroy.
		return managed.ExternalDelete{}, nil
	}

	// A 404 means someone else already did it, which is success as far as
	// reconciliation is concerned.
	_, err := c.service.DoRequest(ctx, "DELETE", fmt.Sprintf("/api/v2/buzz/shares/%v", id), nil)
	if err != nil && !orangehrm.IsNotFound(err) {
		return managed.ExternalDelete{}, errors.Wrap(err, errDelete)
	}

	return managed.ExternalDelete{}, nil
}

func (c *external) Disconnect(_ context.Context) error {
	return nil
}
