// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &ClaimRequestAttachment{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// ClaimRequestAttachmentParameters are the configurable fields of a ClaimRequestAttachment.
//
// These are the fields of the create request body (AddAttachmentsToAClaimRequest), which is
// exactly what a person may write. Anything the server assigns is in
// ClaimRequestAttachmentObservation instead.
type ClaimRequestAttachmentParameters struct {
	// RequestId The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="requestId is immutable"
	RequestId string `json:"requestId"`

	// Description
	// +optional
	Description string `json:"description,omitempty"`

	// Attachment
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Attachment string `json:"attachment"`
}

// ClaimRequestAttachmentObservation are the observable fields of a ClaimRequestAttachment.
//
// These are the fields of the read response (ClaimAttachmentModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type ClaimRequestAttachmentObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Attachment
	Attachment string `json:"attachment,omitempty"`

	// AttachedBy
	AttachedBy string `json:"attachedBy,omitempty"`

	// Date
	Date string `json:"date,omitempty"`
}

// A ClaimRequestAttachmentSpec defines the desired state of a ClaimRequestAttachment.
type ClaimRequestAttachmentSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              ClaimRequestAttachmentParameters `json:"forProvider"`
}

// A ClaimRequestAttachmentStatus represents the observed state of a ClaimRequestAttachment.
type ClaimRequestAttachmentStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 ClaimRequestAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A ClaimRequestAttachment is a managed OrangeHRM claimRequestAttachment.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type ClaimRequestAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClaimRequestAttachmentSpec   `json:"spec"`
	Status ClaimRequestAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClaimRequestAttachmentList contains a list of ClaimRequestAttachment
type ClaimRequestAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClaimRequestAttachment `json:"items"`
}

// ClaimRequestAttachment type metadata.
var (
	ClaimRequestAttachmentKind             = reflect.TypeOf(ClaimRequestAttachment{}).Name()
	ClaimRequestAttachmentGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClaimRequestAttachmentKind}.String()
	ClaimRequestAttachmentKindAPIVersion   = ClaimRequestAttachmentKind + "." + SchemeGroupVersion.String()
	ClaimRequestAttachmentGroupVersionKind = SchemeGroupVersion.WithKind(ClaimRequestAttachmentKind)
)

func init() {
	SchemeBuilder.Register(&ClaimRequestAttachment{}, &ClaimRequestAttachmentList{})
}
