// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

// Package v1alpha1 contains the v1alpha1 group PerformanceConfigTracker resources of the
// OrangeHRM provider.
// +kubebuilder:object:generate=true
// +groupName=orangehrm.crossplane.io
// +versionName=v1alpha1
package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/scheme"
)

// Package type metadata.
const (
	// CRDGroup, not Group: an API may well have a Kind called Group, and a package cannot
	// hold both a const and a type of that name. upjet-generated providers
	// spell it this way for the same reason.
	CRDGroup = "orangehrm.crossplane.io"
	Version  = "v1alpha1"
)

var (
	// SchemeGroupVersion is group version used to register these objects
	SchemeGroupVersion = schema.GroupVersion{Group: CRDGroup, Version: Version}

	// SchemeBuilder is used to add go types to the GroupVersionKind scheme
	SchemeBuilder = &scheme.Builder{GroupVersion: SchemeGroupVersion}
)
