//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTracker) DeepCopyInto(out *PerformanceConfigTracker) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTracker.
func (in *PerformanceConfigTracker) DeepCopy() *PerformanceConfigTracker {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTracker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceConfigTracker) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTrackerList) DeepCopyInto(out *PerformanceConfigTrackerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PerformanceConfigTracker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTrackerList.
func (in *PerformanceConfigTrackerList) DeepCopy() *PerformanceConfigTrackerList {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTrackerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PerformanceConfigTrackerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTrackerObservation) DeepCopyInto(out *PerformanceConfigTrackerObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTrackerObservation.
func (in *PerformanceConfigTrackerObservation) DeepCopy() *PerformanceConfigTrackerObservation {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTrackerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTrackerParameters) DeepCopyInto(out *PerformanceConfigTrackerParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTrackerParameters.
func (in *PerformanceConfigTrackerParameters) DeepCopy() *PerformanceConfigTrackerParameters {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTrackerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTrackerSpec) DeepCopyInto(out *PerformanceConfigTrackerSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTrackerSpec.
func (in *PerformanceConfigTrackerSpec) DeepCopy() *PerformanceConfigTrackerSpec {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTrackerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerformanceConfigTrackerStatus) DeepCopyInto(out *PerformanceConfigTrackerStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerformanceConfigTrackerStatus.
func (in *PerformanceConfigTrackerStatus) DeepCopy() *PerformanceConfigTrackerStatus {
	if in == nil {
		return nil
	}
	out := new(PerformanceConfigTrackerStatus)
	in.DeepCopyInto(out)
	return out
}
