// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &AdminUser{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// AdminUserParameters are the configurable fields of a AdminUser.
//
// These are the fields of the create request body (UpdateAUserRequest), which is
// exactly what a person may write. Anything the server assigns is in
// AdminUserObservation instead.
type AdminUserParameters struct {
	// Username
	// +kubebuilder:validation:Required
	Username string `json:"username"`

	// Password
	// +kubebuilder:validation:Required
	Password string `json:"password"`

	// Status
	// +kubebuilder:validation:Required
	Status bool `json:"status"`

	// UserRoleId
	// +kubebuilder:validation:Required
	UserRoleId int64 `json:"userRoleId"`

	// EmpNumber
	// +kubebuilder:validation:Required
	EmpNumber int64 `json:"empNumber"`
}

// AdminUserObservation are the observable fields of a AdminUser.
//
// These are the fields of the read response (AdminUserModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type AdminUserObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// UserName
	UserName string `json:"userName,omitempty"`

	// Deleted
	Deleted bool `json:"deleted,omitempty"`

	// Status
	Status bool `json:"status,omitempty"`

	// Employee
	Employee string `json:"employee,omitempty"`

	// UserRole
	UserRole string `json:"userRole,omitempty"`
}

// A AdminUserSpec defines the desired state of a AdminUser.
type AdminUserSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              AdminUserParameters `json:"forProvider"`
}

// A AdminUserStatus represents the observed state of a AdminUser.
type AdminUserStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 AdminUserObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A AdminUser is a managed OrangeHRM adminUser.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type AdminUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AdminUserSpec   `json:"spec"`
	Status AdminUserStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdminUserList contains a list of AdminUser
type AdminUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdminUser `json:"items"`
}

// AdminUser type metadata.
var (
	AdminUserKind             = reflect.TypeOf(AdminUser{}).Name()
	AdminUserGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdminUserKind}.String()
	AdminUserKindAPIVersion   = AdminUserKind + "." + SchemeGroupVersion.String()
	AdminUserGroupVersionKind = SchemeGroupVersion.WithKind(AdminUserKind)
)

func init() {
	SchemeBuilder.Register(&AdminUser{}, &AdminUserList{})
}
