// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeSupervisor{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeSupervisorParameters are the configurable fields of a PimEmployeeSupervisor.
//
// These are the fields of the create request body (AddASubordinateToAnEmployeeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeSupervisorObservation instead.
type PimEmployeeSupervisorParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// ReportingMethodId
	// +kubebuilder:validation:Required
	ReportingMethodId int64 `json:"reportingMethodId"`
}

// PimEmployeeSupervisorObservation are the observable fields of a PimEmployeeSupervisor.
//
// These are the fields of the read response (PimEmployeeSupervisorModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeSupervisorObservation struct {
	// Supervisor
	Supervisor string `json:"supervisor,omitempty"`

	// ReportingMethod
	ReportingMethod string `json:"reportingMethod,omitempty"`
}

// A PimEmployeeSupervisorSpec defines the desired state of a PimEmployeeSupervisor.
type PimEmployeeSupervisorSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeSupervisorParameters `json:"forProvider"`
}

// A PimEmployeeSupervisorStatus represents the observed state of a PimEmployeeSupervisor.
type PimEmployeeSupervisorStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeSupervisorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeSupervisor is a managed OrangeHRM pimEmployeeSupervisor.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeSupervisor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeSupervisorSpec   `json:"spec"`
	Status PimEmployeeSupervisorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeSupervisorList contains a list of PimEmployeeSupervisor
type PimEmployeeSupervisorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeSupervisor `json:"items"`
}

// PimEmployeeSupervisor type metadata.
var (
	PimEmployeeSupervisorKind             = reflect.TypeOf(PimEmployeeSupervisor{}).Name()
	PimEmployeeSupervisorGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeSupervisorKind}.String()
	PimEmployeeSupervisorKindAPIVersion   = PimEmployeeSupervisorKind + "." + SchemeGroupVersion.String()
	PimEmployeeSupervisorGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeSupervisorKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeSupervisor{}, &PimEmployeeSupervisorList{})
}
