// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &LeaveHoliday{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// LeaveHolidayParameters are the configurable fields of a LeaveHoliday.
//
// These are the fields of the create request body (CreateAHolidayRequest), which is
// exactly what a person may write. Anything the server assigns is in
// LeaveHolidayObservation instead.
type LeaveHolidayParameters struct {
	// Date
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Date string `json:"date"`

	// Length 0 - working day, 4 - half day
	// +optional
	Length int64 `json:"length,omitempty"`

	// Name
	// +kubebuilder:validation:Required
	// Not a scalar in the API description, so it travels as raw JSON.
	// +kubebuilder:validation:Type=string
	Name string `json:"name"`

	// Recurring
	// +optional
	Recurring bool `json:"recurring"`
}

// LeaveHolidayObservation are the observable fields of a LeaveHoliday.
//
// These are the fields of the read response (LeaveHolidayModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type LeaveHolidayObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// Name
	Name string `json:"name,omitempty"`

	// Date
	Date string `json:"date,omitempty"`

	// Recurring
	Recurring bool `json:"recurring,omitempty"`

	// Length
	Length string `json:"length,omitempty"`

	// LengthName
	LengthName string `json:"lengthName,omitempty"`
}

// A LeaveHolidaySpec defines the desired state of a LeaveHoliday.
type LeaveHolidaySpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              LeaveHolidayParameters `json:"forProvider"`
}

// A LeaveHolidayStatus represents the observed state of a LeaveHoliday.
type LeaveHolidayStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 LeaveHolidayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A LeaveHoliday is a managed OrangeHRM leaveHoliday.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type LeaveHoliday struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   LeaveHolidaySpec   `json:"spec"`
	Status LeaveHolidayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LeaveHolidayList contains a list of LeaveHoliday
type LeaveHolidayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LeaveHoliday `json:"items"`
}

// LeaveHoliday type metadata.
var (
	LeaveHolidayKind             = reflect.TypeOf(LeaveHoliday{}).Name()
	LeaveHolidayGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LeaveHolidayKind}.String()
	LeaveHolidayKindAPIVersion   = LeaveHolidayKind + "." + SchemeGroupVersion.String()
	LeaveHolidayGroupVersionKind = SchemeGroupVersion.WithKind(LeaveHolidayKind)
)

func init() {
	SchemeBuilder.Register(&LeaveHoliday{}, &LeaveHolidayList{})
}
