// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &ClaimRequest{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// ClaimRequestParameters are the configurable fields of a ClaimRequest.
//
// These are the fields of the create request body (CreateMyClaimRequestRequest), which is
// exactly what a person may write. Anything the server assigns is in
// ClaimRequestObservation instead.
type ClaimRequestParameters struct {
	// ClaimEventId
	// +kubebuilder:validation:Required
	ClaimEventId int64 `json:"claimEventId"`

	// CurrencyId
	// +optional
	CurrencyId string `json:"currencyId,omitempty"`

	// Remarks
	// +optional
	Remarks string `json:"remarks,omitempty"`
}

// ClaimRequestObservation are the observable fields of a ClaimRequest.
//
// These are the fields of the read response (ClaimRequestModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type ClaimRequestObservation struct {
	// Id
	Id int64 `json:"id,omitempty"`

	// ReferenceId
	ReferenceId string `json:"referenceId,omitempty"`

	// ClaimEvent
	ClaimEvent string `json:"claimEvent,omitempty"`

	// Currency
	Currency string `json:"currency,omitempty"`

	// Description
	Description string `json:"description,omitempty"`

	// Status
	Status string `json:"status,omitempty"`
}

// A ClaimRequestSpec defines the desired state of a ClaimRequest.
type ClaimRequestSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              ClaimRequestParameters `json:"forProvider"`
}

// A ClaimRequestStatus represents the observed state of a ClaimRequest.
type ClaimRequestStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 ClaimRequestObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A ClaimRequest is a managed OrangeHRM claimRequest.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type ClaimRequest struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClaimRequestSpec   `json:"spec"`
	Status ClaimRequestStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClaimRequestList contains a list of ClaimRequest
type ClaimRequestList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClaimRequest `json:"items"`
}

// ClaimRequest type metadata.
var (
	ClaimRequestKind             = reflect.TypeOf(ClaimRequest{}).Name()
	ClaimRequestGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ClaimRequestKind}.String()
	ClaimRequestKindAPIVersion   = ClaimRequestKind + "." + SchemeGroupVersion.String()
	ClaimRequestGroupVersionKind = SchemeGroupVersion.WithKind(ClaimRequestKind)
)

func init() {
	SchemeBuilder.Register(&ClaimRequest{}, &ClaimRequestList{})
}
