// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &CustomfieldAppliesto{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// CustomfieldAppliestoParameters are the configurable fields of a CustomfieldAppliesto.
//
// These are the fields of the create request body (CustomfieldIdAppliestoPostRequest), which is
// exactly what a person may write. Anything the server assigns is in
// CustomfieldAppliestoObservation instead.
type CustomfieldAppliestoParameters struct {
	// Id The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="id is immutable"
	Id string `json:"id"`

	// ObjectId The id of the object to apply it to, or 0 for every object of its lookup type.
	// +kubebuilder:validation:Required
	ObjectId int64 `json:"ObjectId"`
}

// CustomfieldAppliestoObservation are the observable fields of a CustomfieldAppliesto.
//
// These are the fields of the read response (CustomfieldIdAppliestoPost201Response) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type CustomfieldAppliestoObservation struct {
	// Message
	Message string `json:"message,omitempty"`

	// ObjectId
	ObjectId int64 `json:"ObjectId,omitempty"`

	// ObjectType
	ObjectType string `json:"ObjectType,omitempty"`

	// ObjectName
	ObjectName string `json:"ObjectName,omitempty"`
}

// A CustomfieldAppliestoSpec defines the desired state of a CustomfieldAppliesto.
type CustomfieldAppliestoSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              CustomfieldAppliestoParameters `json:"forProvider"`
}

// A CustomfieldAppliestoStatus represents the observed state of a CustomfieldAppliesto.
type CustomfieldAppliestoStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 CustomfieldAppliestoObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A CustomfieldAppliesto is a managed RT customfieldAppliesto.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rt}
type CustomfieldAppliesto struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   CustomfieldAppliestoSpec   `json:"spec"`
	Status CustomfieldAppliestoStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomfieldAppliestoList contains a list of CustomfieldAppliesto
type CustomfieldAppliestoList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomfieldAppliesto `json:"items"`
}

// CustomfieldAppliesto type metadata.
var (
	CustomfieldAppliestoKind             = reflect.TypeOf(CustomfieldAppliesto{}).Name()
	CustomfieldAppliestoGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomfieldAppliestoKind}.String()
	CustomfieldAppliestoKindAPIVersion   = CustomfieldAppliestoKind + "." + SchemeGroupVersion.String()
	CustomfieldAppliestoGroupVersionKind = SchemeGroupVersion.WithKind(CustomfieldAppliestoKind)
)

func init() {
	SchemeBuilder.Register(&CustomfieldAppliesto{}, &CustomfieldAppliestoList{})
}
