//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLike) DeepCopyInto(out *BuzzShareLike) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLike.
func (in *BuzzShareLike) DeepCopy() *BuzzShareLike {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLike)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuzzShareLike) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLikeList) DeepCopyInto(out *BuzzShareLikeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuzzShareLike, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLikeList.
func (in *BuzzShareLikeList) DeepCopy() *BuzzShareLikeList {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLikeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuzzShareLikeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLikeObservation) DeepCopyInto(out *BuzzShareLikeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLikeObservation.
func (in *BuzzShareLikeObservation) DeepCopy() *BuzzShareLikeObservation {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLikeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLikeParameters) DeepCopyInto(out *BuzzShareLikeParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLikeParameters.
func (in *BuzzShareLikeParameters) DeepCopy() *BuzzShareLikeParameters {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLikeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLikeSpec) DeepCopyInto(out *BuzzShareLikeSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLikeSpec.
func (in *BuzzShareLikeSpec) DeepCopy() *BuzzShareLikeSpec {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLikeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuzzShareLikeStatus) DeepCopyInto(out *BuzzShareLikeStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuzzShareLikeStatus.
func (in *BuzzShareLikeStatus) DeepCopy() *BuzzShareLikeStatus {
	if in == nil {
		return nil
	}
	out := new(BuzzShareLikeStatus)
	in.DeepCopyInto(out)
	return out
}
