// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package v1alpha1

import (
	"reflect"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

// NOTE: no `var _ resource.ModernManaged = &PimEmployeeEmergencyContact{}` assertion here, unlike
// a hand-written provider. The methods that satisfy it are the ones angryjet
// writes, and angryjet LOADS this package to write them -- an assertion that
// fails until it has run is a package that cannot compile until it has run,
// and angryjet then cannot run. The provider still fails to build if the
// methods are missing, because cmd/provider registers these types.

// PimEmployeeEmergencyContactParameters are the configurable fields of a PimEmployeeEmergencyContact.
//
// These are the fields of the create request body (AddAnEmergencyContactToAnEmployeeRequest), which is
// exactly what a person may write. Anything the server assigns is in
// PimEmployeeEmergencyContactObservation instead.
type PimEmployeeEmergencyContactParameters struct {
	// EmpNumber The identifier of the owning resource, from the path.
	// +kubebuilder:validation:Required
	// IMMUTABLE: it is part of the resource's path, so changing it would
	// address a different resource rather than modify this one.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="empNumber is immutable"
	EmpNumber string `json:"empNumber"`

	// Name Specify the name of the emergency contact
	// +kubebuilder:validation:Required
	Name string `json:"name"`

	// Relationship Specify the relationship between the employee and the emergency contact
	// +kubebuilder:validation:Required
	Relationship string `json:"relationship"`

	// HomePhone Specify the home phone number of the emergency contact
	// +kubebuilder:validation:Required
	HomePhone string `json:"homePhone"`

	// OfficePhone Specfiy the office phone number of the emergency contact
	// +kubebuilder:validation:Required
	OfficePhone string `json:"officePhone"`

	// MobilePhone Specify the mobile phone number of the emergency contact
	// +kubebuilder:validation:Required
	MobilePhone string `json:"mobilePhone"`
}

// PimEmployeeEmergencyContactObservation are the observable fields of a PimEmployeeEmergencyContact.
//
// These are the fields of the read response (PimEmpEmergencyContactModel) -- what IS,
// including the fields a person also writes. The controller diffs the two.
type PimEmployeeEmergencyContactObservation struct {
	// Id The numerical ID of the emergency contact
	Id int64 `json:"id,omitempty"`

	// Name The name of the emergency contact
	Name string `json:"name,omitempty"`

	// Relationship The relationship between the employee and the emergency contact
	Relationship string `json:"relationship,omitempty"`

	// HomePhone The contact&#39;s home phone number
	HomePhone string `json:"homePhone,omitempty"`

	// OfficePhone The contact&#39;s office phone number
	OfficePhone string `json:"officePhone,omitempty"`

	// MobilePhone The contact&#39;s mobile phone number
	MobilePhone string `json:"mobilePhone,omitempty"`
}

// A PimEmployeeEmergencyContactSpec defines the desired state of a PimEmployeeEmergencyContact.
type PimEmployeeEmergencyContactSpec struct {
	xpv2.ManagedResourceSpec `json:",inline"`
	ForProvider              PimEmployeeEmergencyContactParameters `json:"forProvider"`
}

// A PimEmployeeEmergencyContactStatus represents the observed state of a PimEmployeeEmergencyContact.
type PimEmployeeEmergencyContactStatus struct {
	xpv2.ManagedResourceStatus `json:",inline"`
	AtProvider                 PimEmployeeEmergencyContactObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// A PimEmployeeEmergencyContact is a managed OrangeHRM pimEmployeeEmergencyContact.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,orangehrm}
type PimEmployeeEmergencyContact struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   PimEmployeeEmergencyContactSpec   `json:"spec"`
	Status PimEmployeeEmergencyContactStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PimEmployeeEmergencyContactList contains a list of PimEmployeeEmergencyContact
type PimEmployeeEmergencyContactList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PimEmployeeEmergencyContact `json:"items"`
}

// PimEmployeeEmergencyContact type metadata.
var (
	PimEmployeeEmergencyContactKind             = reflect.TypeOf(PimEmployeeEmergencyContact{}).Name()
	PimEmployeeEmergencyContactGroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PimEmployeeEmergencyContactKind}.String()
	PimEmployeeEmergencyContactKindAPIVersion   = PimEmployeeEmergencyContactKind + "." + SchemeGroupVersion.String()
	PimEmployeeEmergencyContactGroupVersionKind = SchemeGroupVersion.WithKind(PimEmployeeEmergencyContactKind)
)

func init() {
	SchemeBuilder.Register(&PimEmployeeEmergencyContact{}, &PimEmployeeEmergencyContactList{})
}
