//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContact) DeepCopyInto(out *PimEmployeeEmergencyContact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContact.
func (in *PimEmployeeEmergencyContact) DeepCopy() *PimEmployeeEmergencyContact {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeEmergencyContact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContactList) DeepCopyInto(out *PimEmployeeEmergencyContactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PimEmployeeEmergencyContact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContactList.
func (in *PimEmployeeEmergencyContactList) DeepCopy() *PimEmployeeEmergencyContactList {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PimEmployeeEmergencyContactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContactObservation) DeepCopyInto(out *PimEmployeeEmergencyContactObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContactObservation.
func (in *PimEmployeeEmergencyContactObservation) DeepCopy() *PimEmployeeEmergencyContactObservation {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContactObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContactParameters) DeepCopyInto(out *PimEmployeeEmergencyContactParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContactParameters.
func (in *PimEmployeeEmergencyContactParameters) DeepCopy() *PimEmployeeEmergencyContactParameters {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContactParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContactSpec) DeepCopyInto(out *PimEmployeeEmergencyContactSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContactSpec.
func (in *PimEmployeeEmergencyContactSpec) DeepCopy() *PimEmployeeEmergencyContactSpec {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContactSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PimEmployeeEmergencyContactStatus) DeepCopyInto(out *PimEmployeeEmergencyContactStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PimEmployeeEmergencyContactStatus.
func (in *PimEmployeeEmergencyContactStatus) DeepCopy() *PimEmployeeEmergencyContactStatus {
	if in == nil {
		return nil
	}
	out := new(PimEmployeeEmergencyContactStatus)
	in.DeepCopyInto(out)
	return out
}
