//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecord) DeepCopyInto(out *AttendanceEmployeeRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecord.
func (in *AttendanceEmployeeRecord) DeepCopy() *AttendanceEmployeeRecord {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttendanceEmployeeRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecordList) DeepCopyInto(out *AttendanceEmployeeRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttendanceEmployeeRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecordList.
func (in *AttendanceEmployeeRecordList) DeepCopy() *AttendanceEmployeeRecordList {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttendanceEmployeeRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecordObservation) DeepCopyInto(out *AttendanceEmployeeRecordObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecordObservation.
func (in *AttendanceEmployeeRecordObservation) DeepCopy() *AttendanceEmployeeRecordObservation {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecordParameters) DeepCopyInto(out *AttendanceEmployeeRecordParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecordParameters.
func (in *AttendanceEmployeeRecordParameters) DeepCopy() *AttendanceEmployeeRecordParameters {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecordSpec) DeepCopyInto(out *AttendanceEmployeeRecordSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecordSpec.
func (in *AttendanceEmployeeRecordSpec) DeepCopy() *AttendanceEmployeeRecordSpec {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttendanceEmployeeRecordStatus) DeepCopyInto(out *AttendanceEmployeeRecordStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttendanceEmployeeRecordStatus.
func (in *AttendanceEmployeeRecordStatus) DeepCopy() *AttendanceEmployeeRecordStatus {
	if in == nil {
		return nil
	}
	out := new(AttendanceEmployeeRecordStatus)
	in.DeepCopyInto(out)
	return out
}
