//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRight) DeepCopyInto(out *CustomfieldRight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRight.
func (in *CustomfieldRight) DeepCopy() *CustomfieldRight {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomfieldRight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRightList) DeepCopyInto(out *CustomfieldRightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomfieldRight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRightList.
func (in *CustomfieldRightList) DeepCopy() *CustomfieldRightList {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomfieldRightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRightObservation) DeepCopyInto(out *CustomfieldRightObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRightObservation.
func (in *CustomfieldRightObservation) DeepCopy() *CustomfieldRightObservation {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRightObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRightParameters) DeepCopyInto(out *CustomfieldRightParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRightParameters.
func (in *CustomfieldRightParameters) DeepCopy() *CustomfieldRightParameters {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRightParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRightSpec) DeepCopyInto(out *CustomfieldRightSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRightSpec.
func (in *CustomfieldRightSpec) DeepCopy() *CustomfieldRightSpec {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomfieldRightStatus) DeepCopyInto(out *CustomfieldRightStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomfieldRightStatus.
func (in *CustomfieldRightStatus) DeepCopy() *CustomfieldRightStatus {
	if in == nil {
		return nil
	}
	out := new(CustomfieldRightStatus)
	in.DeepCopyInto(out)
	return out
}
